# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\leroux\Github\PyGMI\PyGMI_files\Config_menu.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Config_menu(object):
    def setupUi(self, Config_menu):
        Config_menu.setObjectName("Config_menu")
        Config_menu.resize(543, 593)
        self.gridLayout = QtWidgets.QGridLayout(Config_menu)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Config_menu)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.macfold = QtWidgets.QLineEdit(Config_menu)
        self.macfold.setObjectName("macfold")
        self.gridLayout.addWidget(self.macfold, 1, 0, 1, 6)
        self.label_2 = QtWidgets.QLabel(Config_menu)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 2)
        self.measfold = QtWidgets.QLineEdit(Config_menu)
        self.measfold.setObjectName("measfold")
        self.gridLayout.addWidget(self.measfold, 3, 0, 1, 6)
        self.label_4 = QtWidgets.QLabel(Config_menu)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 0, 1, 2)
        self.smtpadd = QtWidgets.QLineEdit(Config_menu)
        self.smtpadd.setObjectName("smtpadd")
        self.gridLayout.addWidget(self.smtpadd, 8, 0, 1, 6)
        self.label_5 = QtWidgets.QLabel(Config_menu)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 9, 0, 1, 2)
        self.login = QtWidgets.QLineEdit(Config_menu)
        self.login.setObjectName("login")
        self.gridLayout.addWidget(self.login, 10, 0, 1, 6)
        self.label_6 = QtWidgets.QLabel(Config_menu)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 11, 0, 1, 2)
        self.mdp = QtWidgets.QLineEdit(Config_menu)
        self.mdp.setEchoMode(QtWidgets.QLineEdit.Password)
        self.mdp.setObjectName("mdp")
        self.gridLayout.addWidget(self.mdp, 12, 0, 1, 6)
        self.label_7 = QtWidgets.QLabel(Config_menu)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 13, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(Config_menu)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 15, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Config_menu)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 15, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Config_menu)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 17, 4, 1, 2)
        self.label_3 = QtWidgets.QLabel(Config_menu)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.pointsize = QtWidgets.QSpinBox(Config_menu)
        self.pointsize.setObjectName("pointsize")
        self.gridLayout.addWidget(self.pointsize, 15, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(Config_menu)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 15, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(Config_menu)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 17, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(Config_menu)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 17, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem1, 16, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(Config_menu)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 7, 4, 1, 1)
        self.smtpport = QtWidgets.QSpinBox(Config_menu)
        self.smtpport.setMaximum(100000)
        self.smtpport.setProperty("value", 465)
        self.smtpport.setObjectName("smtpport")
        self.gridLayout.addWidget(self.smtpport, 7, 5, 1, 1)
        self.indep_panels = QtWidgets.QCheckBox(Config_menu)
        self.indep_panels.setChecked(True)
        self.indep_panels.setObjectName("indep_panels")
        self.gridLayout.addWidget(self.indep_panels, 15, 4, 1, 2)

        self.retranslateUi(Config_menu)
        self.buttonBox.accepted.connect(Config_menu.update_values)
        self.buttonBox.rejected.connect(Config_menu.reject)
        self.pushButton.clicked.connect(Config_menu.change_line_color)
        self.pushButton_2.clicked.connect(Config_menu.change_point_color)
        self.pushButton_3.clicked.connect(Config_menu.loadconf)
        self.pushButton_4.clicked.connect(Config_menu.saveconf)
        QtCore.QMetaObject.connectSlotsByName(Config_menu)

    def retranslateUi(self, Config_menu):
        _translate = QtCore.QCoreApplication.translate
        Config_menu.setWindowTitle(_translate("Config_menu", "Dialog"))
        self.label.setText(_translate("Config_menu", "default macro folder"))
        self.macfold.setText(_translate("Config_menu", "macro"))
        self.label_2.setText(_translate("Config_menu", "default data files folder"))
        self.measfold.setText(_translate("Config_menu", "measurements data"))
        self.label_4.setText(_translate("Config_menu", "Smtp server address"))
        self.smtpadd.setText(_translate("Config_menu", "smtp.mail.com"))
        self.label_5.setText(_translate("Config_menu", "Login"))
        self.login.setText(_translate("Config_menu", "blabla@blabla.com"))
        self.label_6.setText(_translate("Config_menu", "Password"))
        self.mdp.setText(_translate("Config_menu", "Password"))
        self.label_7.setText(_translate("Config_menu", "Plot default options"))
        self.pushButton.setText(_translate("Config_menu", "Line color"))
        self.pushButton_2.setText(_translate("Config_menu", "Point color"))
        self.label_3.setText(_translate("Config_menu", "e-mail"))
        self.label_8.setText(_translate("Config_menu", "Point size"))
        self.pushButton_4.setText(_translate("Config_menu", "Save"))
        self.pushButton_3.setText(_translate("Config_menu", "Load"))
        self.label_9.setText(_translate("Config_menu", "Port"))
        self.indep_panels.setText(_translate("Config_menu", "Instruments Panels in\n"
"independent windows"))

