# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\msdguest\Documents\Programmation latest projects\PyGMI\PyGMI-release - v3.1 beta\PyGMI_files\Config_menu.ui'
#
# Created: Mon Aug 03 14:02:21 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Config_menu(object):
    def setupUi(self, Config_menu):
        Config_menu.setObjectName("Config_menu")
        Config_menu.resize(543, 593)
        self.gridLayout = QtGui.QGridLayout(Config_menu)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(Config_menu)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.macfold = QtGui.QLineEdit(Config_menu)
        self.macfold.setObjectName("macfold")
        self.gridLayout.addWidget(self.macfold, 1, 0, 1, 6)
        self.label_2 = QtGui.QLabel(Config_menu)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 2)
        self.measfold = QtGui.QLineEdit(Config_menu)
        self.measfold.setObjectName("measfold")
        self.gridLayout.addWidget(self.measfold, 3, 0, 1, 6)
        self.label_4 = QtGui.QLabel(Config_menu)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 0, 1, 2)
        self.smtpadd = QtGui.QLineEdit(Config_menu)
        self.smtpadd.setObjectName("smtpadd")
        self.gridLayout.addWidget(self.smtpadd, 8, 0, 1, 6)
        self.label_5 = QtGui.QLabel(Config_menu)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 9, 0, 1, 2)
        self.login = QtGui.QLineEdit(Config_menu)
        self.login.setObjectName("login")
        self.gridLayout.addWidget(self.login, 10, 0, 1, 6)
        self.label_6 = QtGui.QLabel(Config_menu)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 11, 0, 1, 2)
        self.mdp = QtGui.QLineEdit(Config_menu)
        self.mdp.setEchoMode(QtGui.QLineEdit.Password)
        self.mdp.setObjectName("mdp")
        self.gridLayout.addWidget(self.mdp, 12, 0, 1, 6)
        self.label_7 = QtGui.QLabel(Config_menu)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 13, 0, 1, 2)
        self.pushButton = QtGui.QPushButton(Config_menu)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 15, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(Config_menu)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 15, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Config_menu)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 17, 4, 1, 2)
        self.label_3 = QtGui.QLabel(Config_menu)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.pointsize = QtGui.QSpinBox(Config_menu)
        self.pointsize.setObjectName("pointsize")
        self.gridLayout.addWidget(self.pointsize, 15, 3, 1, 1)
        self.label_8 = QtGui.QLabel(Config_menu)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 15, 2, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(Config_menu)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 17, 0, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(Config_menu)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 17, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem1, 16, 0, 1, 1)
        self.label_9 = QtGui.QLabel(Config_menu)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 7, 4, 1, 1)
        self.smtpport = QtGui.QSpinBox(Config_menu)
        self.smtpport.setMaximum(100000)
        self.smtpport.setProperty("value", 465)
        self.smtpport.setObjectName("smtpport")
        self.gridLayout.addWidget(self.smtpport, 7, 5, 1, 1)

        self.retranslateUi(Config_menu)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Config_menu.update_values)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Config_menu.reject)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL("clicked()"), Config_menu.change_line_color)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL("clicked()"), Config_menu.change_point_color)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL("clicked()"), Config_menu.loadconf)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL("clicked()"), Config_menu.saveconf)
        QtCore.QMetaObject.connectSlotsByName(Config_menu)

    def retranslateUi(self, Config_menu):
        Config_menu.setWindowTitle(QtGui.QApplication.translate("Config_menu", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Config_menu", "default macro folder", None, QtGui.QApplication.UnicodeUTF8))
        self.macfold.setText(QtGui.QApplication.translate("Config_menu", "macro", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Config_menu", "default data files folder", None, QtGui.QApplication.UnicodeUTF8))
        self.measfold.setText(QtGui.QApplication.translate("Config_menu", "measurements data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Config_menu", "Smtp server address", None, QtGui.QApplication.UnicodeUTF8))
        self.smtpadd.setText(QtGui.QApplication.translate("Config_menu", "smtp.mail.com", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Config_menu", "Login", None, QtGui.QApplication.UnicodeUTF8))
        self.login.setText(QtGui.QApplication.translate("Config_menu", "blabla@blabla.com", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Config_menu", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.mdp.setText(QtGui.QApplication.translate("Config_menu", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Config_menu", "Plot default options", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Config_menu", "Line color", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("Config_menu", "Point color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Config_menu", "e-mail", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Config_menu", "Point size", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("Config_menu", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("Config_menu", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Config_menu", "Port", None, QtGui.QApplication.UnicodeUTF8))

