# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\leroux\Github\PyGMI\PyGMI_files\Graphical_User_Interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PyGMI(object):
    def setupUi(self, PyGMI):
        PyGMI.setObjectName("PyGMI")
        PyGMI.resize(1224, 839)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PyGMI.sizePolicy().hasHeightForWidth())
        PyGMI.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(PyGMI)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Box)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1177, 913))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.instr_IO = Instruments_connection(self.tab_3)
        self.instr_IO.setObjectName("instr_IO")
        self.horizontalLayout_2.addWidget(self.instr_IO)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(500, 0))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.macro_UI = Macro_editor(self.groupBox)
        self.macro_UI.setObjectName("macro_UI")
        self.horizontalLayout_3.addWidget(self.macro_UI)
        self.gridLayout_8.addWidget(self.groupBox, 0, 1, 6, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_50 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_50.setFont(font)
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.gridLayout_3.addWidget(self.label_50, 0, 0, 1, 1)
        self.measMode = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.measMode.setFont(font)
        self.measMode.setDuplicatesEnabled(False)
        self.measMode.setObjectName("measMode")
        self.measMode.addItem("")
        self.measMode.addItem("")
        self.measMode.addItem("")
        self.measMode.addItem("")
        self.measMode.addItem("")
        self.measMode.addItem("")
        self.gridLayout_3.addWidget(self.measMode, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setFamily("12 Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 8pt Bold \"Arial\";")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 1, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(75, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_7.addWidget(self.pushButton_14, 0, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_7.addWidget(self.pushButton_13, 0, 1, 1, 1)
        self.NewPlotWindowTitle = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NewPlotWindowTitle.sizePolicy().hasHeightForWidth())
        self.NewPlotWindowTitle.setSizePolicy(sizePolicy)
        self.NewPlotWindowTitle.setObjectName("NewPlotWindowTitle")
        self.gridLayout_7.addWidget(self.NewPlotWindowTitle, 0, 2, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.groupBox_4)
        self.label_47.setObjectName("label_47")
        self.gridLayout_7.addWidget(self.label_47, 1, 0, 1, 2)
        self.email_address = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.email_address.sizePolicy().hasHeightForWidth())
        self.email_address.setSizePolicy(sizePolicy)
        self.email_address.setText("")
        self.email_address.setObjectName("email_address")
        self.gridLayout_7.addWidget(self.email_address, 2, 0, 1, 3)
        self.gridLayout_8.addWidget(self.groupBox_4, 4, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 0, 2, 1, 1)
        self.anglestep = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.anglestep.setEnabled(False)
        self.anglestep.setMinimum(-1000.0)
        self.anglestep.setMaximum(1000.0)
        self.anglestep.setObjectName("anglestep")
        self.gridLayout_6.addWidget(self.anglestep, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 0, 1, 1, 1)
        self.anglestart = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.anglestart.setEnabled(False)
        self.anglestart.setMinimum(-1000.0)
        self.anglestart.setMaximum(1000.0)
        self.anglestart.setObjectName("anglestart")
        self.gridLayout_6.addWidget(self.anglestart, 1, 0, 1, 1)
        self.anglestop = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.anglestop.setEnabled(False)
        self.anglestop.setMinimum(-1000.0)
        self.anglestop.setMaximum(1000.0)
        self.anglestop.setObjectName("anglestop")
        self.gridLayout_6.addWidget(self.anglestop, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_3, 5, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(0, 8))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_9.addWidget(self.label_9, 0, 0, 1, 1)
        self.V_LR700 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.V_LR700.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.V_LR700.sizePolicy().hasHeightForWidth())
        self.V_LR700.setSizePolicy(sizePolicy)
        self.V_LR700.setMinimumSize(QtCore.QSize(91, 0))
        self.V_LR700.setAlignment(QtCore.Qt.AlignCenter)
        self.V_LR700.setDecimals(6)
        self.V_LR700.setMinimum(-999999999.0)
        self.V_LR700.setMaximum(10000004.0)
        self.V_LR700.setSingleStep(10.0)
        self.V_LR700.setProperty("value", 1.0)
        self.V_LR700.setObjectName("V_LR700")
        self.gridLayout_9.addWidget(self.V_LR700, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(0, 8))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_9.addWidget(self.label_12, 0, 1, 1, 1)
        self.range_LR700 = QtWidgets.QComboBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.range_LR700.sizePolicy().hasHeightForWidth())
        self.range_LR700.setSizePolicy(sizePolicy)
        self.range_LR700.setEditable(False)
        self.range_LR700.setIconSize(QtCore.QSize(16, 16))
        self.range_LR700.setObjectName("range_LR700")
        self.range_LR700.addItem("")
        self.range_LR700.addItem("")
        self.range_LR700.addItem("")
        self.range_LR700.addItem("")
        self.range_LR700.addItem("")
        self.range_LR700.addItem("")
        self.range_LR700.addItem("")
        self.range_LR700.addItem("")
        self.range_LR700.addItem("")
        self.range_LR700.addItem("")
        self.gridLayout_9.addWidget(self.range_LR700, 1, 1, 1, 1)
        self.integ_rate_LR700 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.integ_rate_LR700.sizePolicy().hasHeightForWidth())
        self.integ_rate_LR700.setSizePolicy(sizePolicy)
        self.integ_rate_LR700.setMinimumSize(QtCore.QSize(91, 0))
        self.integ_rate_LR700.setAlignment(QtCore.Qt.AlignCenter)
        self.integ_rate_LR700.setDecimals(3)
        self.integ_rate_LR700.setMaximum(1000000000.0)
        self.integ_rate_LR700.setSingleStep(1.0)
        self.integ_rate_LR700.setProperty("value", 1.0)
        self.integ_rate_LR700.setObjectName("integ_rate_LR700")
        self.gridLayout_9.addWidget(self.integ_rate_LR700, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(0, 8))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 0, 2, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName("gridLayout")
        self.I_source_setpoint_2 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.I_source_setpoint_2.setMinimumSize(QtCore.QSize(91, 0))
        self.I_source_setpoint_2.setAlignment(QtCore.Qt.AlignCenter)
        self.I_source_setpoint_2.setDecimals(3)
        self.I_source_setpoint_2.setMaximum(10000000.0)
        self.I_source_setpoint_2.setSingleStep(10.0)
        self.I_source_setpoint_2.setProperty("value", 100.0)
        self.I_source_setpoint_2.setObjectName("I_source_setpoint_2")
        self.gridLayout.addWidget(self.I_source_setpoint_2, 4, 3, 1, 1)
        self.I_source_setpoint = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.I_source_setpoint.setMinimumSize(QtCore.QSize(91, 0))
        self.I_source_setpoint.setAlignment(QtCore.Qt.AlignCenter)
        self.I_source_setpoint.setDecimals(3)
        self.I_source_setpoint.setMaximum(10000000.0)
        self.I_source_setpoint.setSingleStep(10.0)
        self.I_source_setpoint.setProperty("value", 10.0)
        self.I_source_setpoint.setObjectName("I_source_setpoint")
        self.gridLayout.addWidget(self.I_source_setpoint, 4, 0, 1, 3)
        self.label_70 = QtWidgets.QLabel(self.groupBox_5)
        self.label_70.setAlignment(QtCore.Qt.AlignCenter)
        self.label_70.setObjectName("label_70")
        self.gridLayout.addWidget(self.label_70, 6, 1, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.groupBox_5)
        self.label_69.setAlignment(QtCore.Qt.AlignCenter)
        self.label_69.setObjectName("label_69")
        self.gridLayout.addWidget(self.label_69, 3, 6, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.groupBox_5)
        self.label_68.setAlignment(QtCore.Qt.AlignCenter)
        self.label_68.setObjectName("label_68")
        self.gridLayout.addWidget(self.label_68, 3, 3, 1, 2)
        self.label_49 = QtWidgets.QLabel(self.groupBox_5)
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.gridLayout.addWidget(self.label_49, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 6, 1, 1)
        self.mesure_speed = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.mesure_speed.setMinimumSize(QtCore.QSize(91, 0))
        self.mesure_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.mesure_speed.setDecimals(2)
        self.mesure_speed.setMinimum(0.01)
        self.mesure_speed.setMaximum(60.0)
        self.mesure_speed.setSingleStep(0.1)
        self.mesure_speed.setProperty("value", 5.0)
        self.mesure_speed.setObjectName("mesure_speed")
        self.gridLayout.addWidget(self.mesure_speed, 7, 0, 1, 3)
        self.label_81 = QtWidgets.QLabel(self.groupBox_5)
        self.label_81.setAlignment(QtCore.Qt.AlignCenter)
        self.label_81.setObjectName("label_81")
        self.gridLayout.addWidget(self.label_81, 11, 6, 1, 1)
        self.repeat_points = QtWidgets.QSpinBox(self.groupBox_5)
        self.repeat_points.setAlignment(QtCore.Qt.AlignCenter)
        self.repeat_points.setMinimum(1)
        self.repeat_points.setMaximum(100000000)
        self.repeat_points.setProperty("value", 1)
        self.repeat_points.setObjectName("repeat_points")
        self.gridLayout.addWidget(self.repeat_points, 7, 6, 1, 1)
        self.B_Y_setpoint = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.B_Y_setpoint.setEnabled(True)
        self.B_Y_setpoint.setMinimumSize(QtCore.QSize(91, 0))
        self.B_Y_setpoint.setAlignment(QtCore.Qt.AlignCenter)
        self.B_Y_setpoint.setDecimals(4)
        self.B_Y_setpoint.setMinimum(-9.0)
        self.B_Y_setpoint.setMaximum(9.0)
        self.B_Y_setpoint.setSingleStep(0.1)
        self.B_Y_setpoint.setProperty("value", 0.0)
        self.B_Y_setpoint.setObjectName("B_Y_setpoint")
        self.gridLayout.addWidget(self.B_Y_setpoint, 18, 3, 1, 1)
        self.B_X_setpoint = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.B_X_setpoint.setEnabled(True)
        self.B_X_setpoint.setMinimumSize(QtCore.QSize(91, 0))
        self.B_X_setpoint.setAlignment(QtCore.Qt.AlignCenter)
        self.B_X_setpoint.setDecimals(4)
        self.B_X_setpoint.setMinimum(-9.0)
        self.B_X_setpoint.setMaximum(9.0)
        self.B_X_setpoint.setSingleStep(0.1)
        self.B_X_setpoint.setProperty("value", 0.0)
        self.B_X_setpoint.setObjectName("B_X_setpoint")
        self.gridLayout.addWidget(self.B_X_setpoint, 18, 1, 1, 1)
        self.V_setpoint_2 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.V_setpoint_2.setEnabled(True)
        self.V_setpoint_2.setMinimumSize(QtCore.QSize(91, 0))
        self.V_setpoint_2.setAlignment(QtCore.Qt.AlignCenter)
        self.V_setpoint_2.setDecimals(6)
        self.V_setpoint_2.setMinimum(-1000000000.0)
        self.V_setpoint_2.setMaximum(10000004.0)
        self.V_setpoint_2.setSingleStep(10.0)
        self.V_setpoint_2.setProperty("value", 1.0)
        self.V_setpoint_2.setObjectName("V_setpoint_2")
        self.gridLayout.addWidget(self.V_setpoint_2, 12, 3, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.groupBox_5)
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.gridLayout.addWidget(self.label_56, 11, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 19, 0, 1, 2)
        self.V_setpoint_1 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.V_setpoint_1.setEnabled(True)
        self.V_setpoint_1.setMinimumSize(QtCore.QSize(91, 0))
        self.V_setpoint_1.setAlignment(QtCore.Qt.AlignCenter)
        self.V_setpoint_1.setDecimals(6)
        self.V_setpoint_1.setMinimum(-999999999.0)
        self.V_setpoint_1.setMaximum(10000004.0)
        self.V_setpoint_1.setSingleStep(10.0)
        self.V_setpoint_1.setProperty("value", 1.0)
        self.V_setpoint_1.setObjectName("V_setpoint_1")
        self.gridLayout.addWidget(self.V_setpoint_1, 12, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 15, 0, 2, 3)
        self.mesure_delay = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.mesure_delay.setMinimumSize(QtCore.QSize(91, 0))
        self.mesure_delay.setAlignment(QtCore.Qt.AlignCenter)
        self.mesure_delay.setDecimals(1)
        self.mesure_delay.setMaximum(200000.0)
        self.mesure_delay.setSingleStep(0.1)
        self.mesure_delay.setProperty("value", 1.0)
        self.mesure_delay.setObjectName("mesure_delay")
        self.gridLayout.addWidget(self.mesure_delay, 7, 3, 1, 1)
        self.B_Z_setpoint = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.B_Z_setpoint.setEnabled(True)
        self.B_Z_setpoint.setMinimumSize(QtCore.QSize(91, 0))
        self.B_Z_setpoint.setAlignment(QtCore.Qt.AlignCenter)
        self.B_Z_setpoint.setDecimals(4)
        self.B_Z_setpoint.setMinimum(-9.0)
        self.B_Z_setpoint.setMaximum(9.0)
        self.B_Z_setpoint.setSingleStep(0.5)
        self.B_Z_setpoint.setProperty("value", 0.0)
        self.B_Z_setpoint.setObjectName("B_Z_setpoint")
        self.gridLayout.addWidget(self.B_Z_setpoint, 18, 6, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.groupBox_5)
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.gridLayout.addWidget(self.label_51, 17, 1, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.groupBox_5)
        self.label_73.setAlignment(QtCore.Qt.AlignCenter)
        self.label_73.setObjectName("label_73")
        self.gridLayout.addWidget(self.label_73, 17, 3, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.groupBox_5)
        self.label_82.setAlignment(QtCore.Qt.AlignCenter)
        self.label_82.setObjectName("label_82")
        self.gridLayout.addWidget(self.label_82, 11, 3, 1, 1)
        self.V_setpoint_3 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.V_setpoint_3.setEnabled(True)
        self.V_setpoint_3.setMinimumSize(QtCore.QSize(91, 0))
        self.V_setpoint_3.setAlignment(QtCore.Qt.AlignCenter)
        self.V_setpoint_3.setDecimals(6)
        self.V_setpoint_3.setMinimum(-1000000000.0)
        self.V_setpoint_3.setMaximum(1000000000.0)
        self.V_setpoint_3.setSingleStep(10.0)
        self.V_setpoint_3.setProperty("value", 1.0)
        self.V_setpoint_3.setObjectName("V_setpoint_3")
        self.gridLayout.addWidget(self.V_setpoint_3, 12, 6, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.groupBox_5)
        self.label_71.setAlignment(QtCore.Qt.AlignCenter)
        self.label_71.setObjectName("label_71")
        self.gridLayout.addWidget(self.label_71, 17, 6, 1, 1)
        self.I_source_setpoint_3 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.I_source_setpoint_3.setEnabled(True)
        self.I_source_setpoint_3.setMinimumSize(QtCore.QSize(91, 0))
        self.I_source_setpoint_3.setAlignment(QtCore.Qt.AlignCenter)
        self.I_source_setpoint_3.setDecimals(3)
        self.I_source_setpoint_3.setMaximum(10000000.0)
        self.I_source_setpoint_3.setSingleStep(10.0)
        self.I_source_setpoint_3.setProperty("value", 100.0)
        self.I_source_setpoint_3.setObjectName("I_source_setpoint_3")
        self.gridLayout.addWidget(self.I_source_setpoint_3, 4, 6, 1, 1)
        self.savefile_txt_input = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savefile_txt_input.sizePolicy().hasHeightForWidth())
        self.savefile_txt_input.setSizePolicy(sizePolicy)
        self.savefile_txt_input.setObjectName("savefile_txt_input")
        self.gridLayout.addWidget(self.savefile_txt_input, 21, 0, 1, 8)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_4.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 19, 6, 1, 1, QtCore.Qt.AlignRight)
        self.IV_voltage_criterion = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.IV_voltage_criterion.setEnabled(False)
        self.IV_voltage_criterion.setMinimumSize(QtCore.QSize(91, 0))
        self.IV_voltage_criterion.setAlignment(QtCore.Qt.AlignCenter)
        self.IV_voltage_criterion.setDecimals(3)
        self.IV_voltage_criterion.setMaximum(100000000.0)
        self.IV_voltage_criterion.setSingleStep(10.0)
        self.IV_voltage_criterion.setProperty("value", 100.0)
        self.IV_voltage_criterion.setObjectName("IV_voltage_criterion")
        self.gridLayout.addWidget(self.IV_voltage_criterion, 10, 6, 1, 1)
        self.voltage_criterion_on = QtWidgets.QCheckBox(self.groupBox_5)
        self.voltage_criterion_on.setEnabled(False)
        self.voltage_criterion_on.setObjectName("voltage_criterion_on")
        self.gridLayout.addWidget(self.voltage_criterion_on, 8, 6, 1, 1)
        self.mesure_delay_2 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.mesure_delay_2.setEnabled(False)
        self.mesure_delay_2.setMinimumSize(QtCore.QSize(91, 0))
        self.mesure_delay_2.setAlignment(QtCore.Qt.AlignCenter)
        self.mesure_delay_2.setDecimals(1)
        self.mesure_delay_2.setMaximum(200000.0)
        self.mesure_delay_2.setSingleStep(0.1)
        self.mesure_delay_2.setProperty("value", 1.0)
        self.mesure_delay_2.setObjectName("mesure_delay_2")
        self.gridLayout.addWidget(self.mesure_delay_2, 10, 1, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.groupBox_5)
        self.label_72.setAlignment(QtCore.Qt.AlignCenter)
        self.label_72.setObjectName("label_72")
        self.gridLayout.addWidget(self.label_72, 8, 1, 1, 1)
        self.mesure_delay_3 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.mesure_delay_3.setMinimumSize(QtCore.QSize(91, 0))
        self.mesure_delay_3.setAlignment(QtCore.Qt.AlignCenter)
        self.mesure_delay_3.setDecimals(1)
        self.mesure_delay_3.setMaximum(200000.0)
        self.mesure_delay_3.setSingleStep(0.1)
        self.mesure_delay_3.setProperty("value", 1.0)
        self.mesure_delay_3.setObjectName("mesure_delay_3")
        self.gridLayout.addWidget(self.mesure_delay_3, 10, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 3, 2, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 8, 3, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Plot2D_1 = Plot2DDataWidget(self.tab_2)
        self.Plot2D_1.setObjectName("Plot2D_1")
        self.gridLayout_4.addWidget(self.Plot2D_1, 0, 0, 1, 1)
        self.Plot2D_2 = Plot2DDataWidget(self.tab_2)
        self.Plot2D_2.setObjectName("Plot2D_2")
        self.gridLayout_4.addWidget(self.Plot2D_2, 0, 1, 1, 1)
        self.Plot2D_3 = Plot2DDataWidget(self.tab_2)
        self.Plot2D_3.setObjectName("Plot2D_3")
        self.gridLayout_4.addWidget(self.Plot2D_3, 1, 0, 1, 1)
        self.Plot2D_4 = Plot2DDataWidget(self.tab_2)
        self.Plot2D_4.setObjectName("Plot2D_4")
        self.gridLayout_4.addWidget(self.Plot2D_4, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.instr_mdi = QtWidgets.QMdiArea(self.tab_6)
        self.instr_mdi.setFrameShape(QtWidgets.QFrame.Panel)
        self.instr_mdi.setFrameShadow(QtWidgets.QFrame.Plain)
        self.instr_mdi.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.instr_mdi.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.instr_mdi.setViewMode(QtWidgets.QMdiArea.SubWindowView)
        self.instr_mdi.setObjectName("instr_mdi")
        self.gridLayout_2.addWidget(self.instr_mdi, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_3 = QtWidgets.QLabel(self.tab_4)
        self.label_3.setGeometry(QtCore.QRect(20, 31, 269, 13))
        self.label_3.setObjectName("label_3")
        self.B_x = QtWidgets.QLineEdit(self.tab_4)
        self.B_x.setEnabled(False)
        self.B_x.setGeometry(QtCore.QRect(28, 69, 110, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B_x.sizePolicy().hasHeightForWidth())
        self.B_x.setSizePolicy(sizePolicy)
        self.B_x.setFrame(True)
        self.B_x.setReadOnly(False)
        self.B_x.setObjectName("B_x")
        self.B_y = QtWidgets.QLineEdit(self.tab_4)
        self.B_y.setEnabled(False)
        self.B_y.setGeometry(QtCore.QRect(157, 69, 126, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B_y.sizePolicy().hasHeightForWidth())
        self.B_y.setSizePolicy(sizePolicy)
        self.B_y.setFrame(True)
        self.B_y.setReadOnly(False)
        self.B_y.setObjectName("B_y")
        self.label_78 = QtWidgets.QLabel(self.tab_4)
        self.label_78.setGeometry(QtCore.QRect(301, 50, 126, 13))
        self.label_78.setAlignment(QtCore.Qt.AlignCenter)
        self.label_78.setObjectName("label_78")
        self.label_77 = QtWidgets.QLabel(self.tab_4)
        self.label_77.setGeometry(QtCore.QRect(157, 50, 126, 13))
        self.label_77.setAlignment(QtCore.Qt.AlignCenter)
        self.label_77.setObjectName("label_77")
        self.B_z = QtWidgets.QLineEdit(self.tab_4)
        self.B_z.setEnabled(False)
        self.B_z.setGeometry(QtCore.QRect(301, 69, 126, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B_z.sizePolicy().hasHeightForWidth())
        self.B_z.setSizePolicy(sizePolicy)
        self.B_z.setFrame(True)
        self.B_z.setReadOnly(False)
        self.B_z.setObjectName("B_z")
        self.label_52 = QtWidgets.QLabel(self.tab_4)
        self.label_52.setGeometry(QtCore.QRect(20, 50, 131, 13))
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout_5.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        PyGMI.setCentralWidget(self.centralwidget)

        self.retranslateUi(PyGMI)
        self.tabWidget.setCurrentIndex(1)
        self.range_LR700.setCurrentIndex(9)
        self.pushButton.clicked.connect(PyGMI.switch_measurements_state)
        self.pushButton_4.clicked.connect(PyGMI.savefile_txt_input_open)
        self.pushButton_13.clicked.connect(PyGMI.create_new_plotwidget)
        self.pushButton_14.clicked.connect(PyGMI.create_config_menu)
        self.pushButton_3.clicked.connect(PyGMI.update_list_of_meas_program)
        QtCore.QMetaObject.connectSlotsByName(PyGMI)
        PyGMI.setTabOrder(self.savefile_txt_input, self.pushButton)

    def retranslateUi(self, PyGMI):
        _translate = QtCore.QCoreApplication.translate
        PyGMI.setWindowTitle(_translate("PyGMI", "PyGMI v3.1 - Python Generic Measurements Interface"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("PyGMI", "Instr I/O"))
        self.groupBox.setTitle(_translate("PyGMI", "Macro Editor"))
        self.groupBox_2.setTitle(_translate("PyGMI", "Single shot Measurements"))
        self.label_50.setText(_translate("PyGMI", "Measurements Program"))
        self.measMode.setItemText(0, _translate("PyGMI", "B Rem mode"))
        self.measMode.setItemText(1, _translate("PyGMI", "M vs H mode"))
        self.measMode.setItemText(2, _translate("PyGMI", "+I/-I mode"))
        self.measMode.setItemText(3, _translate("PyGMI", "M vs T mode"))
        self.measMode.setItemText(4, _translate("PyGMI", "IV curve (PC trigger)"))
        self.measMode.setItemText(5, _translate("PyGMI", "IV curve (T-link cable, not finished yet)"))
        self.pushButton.setText(_translate("PyGMI", "Start\n"
"Measurements"))
        self.pushButton_3.setText(_translate("PyGMI", "Update\n"
"Program List"))
        self.groupBox_4.setTitle(_translate("PyGMI", "Plots"))
        self.pushButton_14.setText(_translate("PyGMI", "Config Menu"))
        self.pushButton_13.setText(_translate("PyGMI", "New Plot Window"))
        self.NewPlotWindowTitle.setText(_translate("PyGMI", "New Plot Window Title"))
        self.label_47.setText(_translate("PyGMI", "E-mail alert address"))
        self.groupBox_3.setTitle(_translate("PyGMI", "Angle"))
        self.label_7.setText(_translate("PyGMI", "Step"))
        self.anglestep.setSuffix(_translate("PyGMI", " °"))
        self.label_6.setText(_translate("PyGMI", "Stop"))
        self.anglestart.setSuffix(_translate("PyGMI", " °"))
        self.anglestop.setSuffix(_translate("PyGMI", " °"))
        self.label_4.setText(_translate("PyGMI", "Start"))
        self.groupBox_6.setTitle(_translate("PyGMI", "LR700"))
        self.label_9.setText(_translate("PyGMI", "Integration Rate"))
        self.V_LR700.setSuffix(_translate("PyGMI", " µV"))
        self.label_12.setText(_translate("PyGMI", "Range"))
        self.range_LR700.setItemText(0, _translate("PyGMI", "2 mΩ"))
        self.range_LR700.setItemText(1, _translate("PyGMI", "20 mΩ"))
        self.range_LR700.setItemText(2, _translate("PyGMI", "200 mΩ"))
        self.range_LR700.setItemText(3, _translate("PyGMI", "2 Ω"))
        self.range_LR700.setItemText(4, _translate("PyGMI", "20 Ω"))
        self.range_LR700.setItemText(5, _translate("PyGMI", "200 Ω"))
        self.range_LR700.setItemText(6, _translate("PyGMI", "2 kΩ"))
        self.range_LR700.setItemText(7, _translate("PyGMI", "20 kΩ"))
        self.range_LR700.setItemText(8, _translate("PyGMI", "200 kΩ"))
        self.range_LR700.setItemText(9, _translate("PyGMI", "2 MΩ"))
        self.integ_rate_LR700.setSuffix(_translate("PyGMI", " s"))
        self.label_11.setText(_translate("PyGMI", "Excitation"))
        self.groupBox_5.setTitle(_translate("PyGMI", "Parameters"))
        self.I_source_setpoint_2.setSuffix(_translate("PyGMI", " µA"))
        self.I_source_setpoint.setSuffix(_translate("PyGMI", " µA"))
        self.label_70.setText(_translate("PyGMI", "Measurements\n"
"speed"))
        self.label_69.setText(_translate("PyGMI", "Current 3"))
        self.label_68.setText(_translate("PyGMI", "Current 2"))
        self.label_49.setText(_translate("PyGMI", "Current 1"))
        self.label_10.setText(_translate("PyGMI", "Repeat\n"
" each point"))
        self.mesure_speed.setSuffix(_translate("PyGMI", " * 16.7 ms"))
        self.label_81.setText(_translate("PyGMI", "Voltage 3"))
        self.repeat_points.setSuffix(_translate("PyGMI", " times"))
        self.B_Y_setpoint.setSuffix(_translate("PyGMI", " T"))
        self.B_X_setpoint.setSuffix(_translate("PyGMI", " T"))
        self.V_setpoint_2.setSuffix(_translate("PyGMI", "  µV"))
        self.label_56.setText(_translate("PyGMI", "Voltage 1"))
        self.label.setText(_translate("PyGMI", "Save file :"))
        self.V_setpoint_1.setSuffix(_translate("PyGMI", " µV"))
        self.label_2.setText(_translate("PyGMI", "Target field"))
        self.mesure_delay.setSuffix(_translate("PyGMI", " ms"))
        self.B_Z_setpoint.setSuffix(_translate("PyGMI", " T"))
        self.label_51.setText(_translate("PyGMI", "Start"))
        self.label_73.setText(_translate("PyGMI", "Stop"))
        self.label_82.setText(_translate("PyGMI", "Voltage 2"))
        self.V_setpoint_3.setSuffix(_translate("PyGMI", "  µV"))
        self.label_71.setText(_translate("PyGMI", "Step"))
        self.I_source_setpoint_3.setSuffix(_translate("PyGMI", " µA"))
        self.savefile_txt_input.setText(_translate("PyGMI", "measurements data/default.txt"))
        self.pushButton_4.setText(_translate("PyGMI", "..."))
        self.IV_voltage_criterion.setSuffix(_translate("PyGMI", " µV"))
        self.voltage_criterion_on.setText(_translate("PyGMI", "Voltage criterion"))
        self.mesure_delay_2.setSuffix(_translate("PyGMI", " ms"))
        self.label_72.setText(_translate("PyGMI", "Delay after I turn ON"))
        self.mesure_delay_3.setSuffix(_translate("PyGMI", " ms"))
        self.label_5.setText(_translate("PyGMI", "Time between \n"
" measurements\n"
"cycles"))
        self.label_8.setText(_translate("PyGMI", "Integration Rate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("PyGMI", "Measurements"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("PyGMI", "Detailed Graphs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("PyGMI", "Instruments panel"))
        self.label_3.setText(_translate("PyGMI", "Current persistent field"))
        self.label_78.setText(_translate("PyGMI", "Z"))
        self.label_77.setText(_translate("PyGMI", "Y"))
        self.label_52.setText(_translate("PyGMI", "X"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("PyGMI", "Misc"))

from .Instruments_connection import Instruments_connection
from .Macro_editor import Macro_editor
from .Plot2DDataWidget import Plot2DDataWidget
