# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\msdguest\Documents\Programmation latest projects\PyGMI\PyGMI-release - v3.1 beta\PyGMI_files\Graphical_User_Interface.ui'
#
# Created: Mon Aug 03 14:02:21 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_PyGMI(object):
    def setupUi(self, PyGMI):
        PyGMI.setObjectName("PyGMI")
        PyGMI.resize(1638, 786)
        self.centralwidget = QtGui.QWidget(PyGMI)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.instr_IO = Instruments_connection(self.tab_3)
        self.instr_IO.setObjectName("instr_IO")
        self.horizontalLayout_2.addWidget(self.instr_IO)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.label_47 = QtGui.QLabel(self.tab)
        self.label_47.setGeometry(QtCore.QRect(20, 640, 141, 16))
        self.label_47.setObjectName("label_47")
        self.email_address = QtGui.QLineEdit(self.tab)
        self.email_address.setGeometry(QtCore.QRect(20, 660, 291, 22))
        self.email_address.setText("")
        self.email_address.setObjectName("email_address")
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 460, 501, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.measMode = QtGui.QComboBox(self.groupBox_2)
        self.measMode.setGeometry(QtCore.QRect(10, 40, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.measMode.setFont(font)
        self.measMode.setDuplicatesEnabled(False)
        self.measMode.setObjectName("measMode")
        self.measMode.addItem("")
        self.measMode.addItem("")
        self.measMode.addItem("")
        self.measMode.addItem("")
        self.measMode.addItem("")
        self.measMode.addItem("")
        self.label_50 = QtGui.QLabel(self.groupBox_2)
        self.label_50.setGeometry(QtCore.QRect(10, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_50.setFont(font)
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.pushButton = QtGui.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(360, 40, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 40, 71, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 560, 481, 71))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton_13 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_13.setGeometry(QtCore.QRect(10, 20, 131, 41))
        self.pushButton_13.setObjectName("pushButton_13")
        self.NewPlotWindowTitle = QtGui.QLineEdit(self.groupBox_4)
        self.NewPlotWindowTitle.setGeometry(QtCore.QRect(160, 21, 291, 41))
        self.NewPlotWindowTitle.setObjectName("NewPlotWindowTitle")
        self.pushButton_14 = QtGui.QPushButton(self.tab)
        self.pushButton_14.setGeometry(QtCore.QRect(350, 650, 131, 41))
        self.pushButton_14.setObjectName("pushButton_14")
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(520, 10, 1081, 681))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.macro_UI = Macro_editor(self.groupBox)
        self.macro_UI.setObjectName("macro_UI")
        self.horizontalLayout_3.addWidget(self.macro_UI)
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 501, 431))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName("gridLayout")
        self.I_source_setpoint = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.I_source_setpoint.setMinimumSize(QtCore.QSize(91, 0))
        self.I_source_setpoint.setAlignment(QtCore.Qt.AlignCenter)
        self.I_source_setpoint.setDecimals(1)
        self.I_source_setpoint.setMaximum(10000000.0)
        self.I_source_setpoint.setSingleStep(10.0)
        self.I_source_setpoint.setProperty("value", 100.0)
        self.I_source_setpoint.setObjectName("I_source_setpoint")
        self.gridLayout.addWidget(self.I_source_setpoint, 1, 0, 1, 3)
        self.label_68 = QtGui.QLabel(self.groupBox_5)
        self.label_68.setAlignment(QtCore.Qt.AlignCenter)
        self.label_68.setObjectName("label_68")
        self.gridLayout.addWidget(self.label_68, 0, 4, 1, 2)
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_4.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 18, 10, 1, 1)
        self.mesure_speed = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.mesure_speed.setMinimumSize(QtCore.QSize(91, 0))
        self.mesure_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.mesure_speed.setDecimals(2)
        self.mesure_speed.setMinimum(0.01)
        self.mesure_speed.setMaximum(60.0)
        self.mesure_speed.setSingleStep(0.1)
        self.mesure_speed.setProperty("value", 5.0)
        self.mesure_speed.setObjectName("mesure_speed")
        self.gridLayout.addWidget(self.mesure_speed, 4, 0, 1, 3)
        self.I_source_setpoint_2 = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.I_source_setpoint_2.setMinimumSize(QtCore.QSize(91, 0))
        self.I_source_setpoint_2.setAlignment(QtCore.Qt.AlignCenter)
        self.I_source_setpoint_2.setDecimals(1)
        self.I_source_setpoint_2.setMaximum(10000000.0)
        self.I_source_setpoint_2.setSingleStep(10.0)
        self.I_source_setpoint_2.setProperty("value", 100.0)
        self.I_source_setpoint_2.setObjectName("I_source_setpoint_2")
        self.gridLayout.addWidget(self.I_source_setpoint_2, 1, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_5)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 14, 0, 1, 6)
        self.label_52 = QtGui.QLabel(self.groupBox_5)
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.gridLayout.addWidget(self.label_52, 15, 0, 1, 4)
        self.repeat_points = QtGui.QSpinBox(self.groupBox_5)
        self.repeat_points.setAlignment(QtCore.Qt.AlignCenter)
        self.repeat_points.setMinimum(1)
        self.repeat_points.setProperty("value", 1)
        self.repeat_points.setObjectName("repeat_points")
        self.gridLayout.addWidget(self.repeat_points, 4, 7, 1, 1)
        self.savefile_txt_input = QtGui.QLineEdit(self.groupBox_5)
        self.savefile_txt_input.setObjectName("savefile_txt_input")
        self.gridLayout.addWidget(self.savefile_txt_input, 18, 0, 1, 10)
        self.label_77 = QtGui.QLabel(self.groupBox_5)
        self.label_77.setAlignment(QtCore.Qt.AlignCenter)
        self.label_77.setObjectName("label_77")
        self.gridLayout.addWidget(self.label_77, 15, 4, 1, 1)
        self.label_78 = QtGui.QLabel(self.groupBox_5)
        self.label_78.setAlignment(QtCore.Qt.AlignCenter)
        self.label_78.setObjectName("label_78")
        self.gridLayout.addWidget(self.label_78, 15, 7, 1, 1)
        self.V_setpoint_1 = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.V_setpoint_1.setMinimumSize(QtCore.QSize(91, 0))
        self.V_setpoint_1.setAlignment(QtCore.Qt.AlignCenter)
        self.V_setpoint_1.setDecimals(6)
        self.V_setpoint_1.setMinimum(-1000000000.0)
        self.V_setpoint_1.setMaximum(10000004.0)
        self.V_setpoint_1.setSingleStep(10.0)
        self.V_setpoint_1.setProperty("value", 1.0)
        self.V_setpoint_1.setObjectName("V_setpoint_1")
        self.gridLayout.addWidget(self.V_setpoint_1, 7, 0, 1, 3)
        self.label_49 = QtGui.QLabel(self.groupBox_5)
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.gridLayout.addWidget(self.label_49, 0, 1, 1, 1)
        self.V_setpoint_3 = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.V_setpoint_3.setMinimumSize(QtCore.QSize(91, 0))
        self.V_setpoint_3.setAlignment(QtCore.Qt.AlignCenter)
        self.V_setpoint_3.setDecimals(6)
        self.V_setpoint_3.setMinimum(-1000000000.0)
        self.V_setpoint_3.setMaximum(10000004.0)
        self.V_setpoint_3.setSingleStep(10.0)
        self.V_setpoint_3.setProperty("value", 1.0)
        self.V_setpoint_3.setObjectName("V_setpoint_3")
        self.gridLayout.addWidget(self.V_setpoint_3, 7, 7, 1, 1)
        self.mesure_delay = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.mesure_delay.setMinimumSize(QtCore.QSize(91, 0))
        self.mesure_delay.setAlignment(QtCore.Qt.AlignCenter)
        self.mesure_delay.setDecimals(1)
        self.mesure_delay.setMaximum(200000.0)
        self.mesure_delay.setSingleStep(0.1)
        self.mesure_delay.setProperty("value", 1000.0)
        self.mesure_delay.setObjectName("mesure_delay")
        self.gridLayout.addWidget(self.mesure_delay, 4, 4, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_5)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 17, 0, 1, 2)
        self.label_56 = QtGui.QLabel(self.groupBox_5)
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.gridLayout.addWidget(self.label_56, 6, 0, 1, 3)
        self.label_69 = QtGui.QLabel(self.groupBox_5)
        self.label_69.setAlignment(QtCore.Qt.AlignCenter)
        self.label_69.setObjectName("label_69")
        self.gridLayout.addWidget(self.label_69, 0, 7, 1, 1)
        self.label_81 = QtGui.QLabel(self.groupBox_5)
        self.label_81.setAlignment(QtCore.Qt.AlignCenter)
        self.label_81.setObjectName("label_81")
        self.gridLayout.addWidget(self.label_81, 6, 7, 1, 1)
        self.label_82 = QtGui.QLabel(self.groupBox_5)
        self.label_82.setAlignment(QtCore.Qt.AlignCenter)
        self.label_82.setObjectName("label_82")
        self.gridLayout.addWidget(self.label_82, 6, 4, 1, 1)
        self.label_70 = QtGui.QLabel(self.groupBox_5)
        self.label_70.setAlignment(QtCore.Qt.AlignCenter)
        self.label_70.setObjectName("label_70")
        self.gridLayout.addWidget(self.label_70, 3, 1, 1, 1)
        self.V_setpoint_2 = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.V_setpoint_2.setMinimumSize(QtCore.QSize(91, 0))
        self.V_setpoint_2.setAlignment(QtCore.Qt.AlignCenter)
        self.V_setpoint_2.setDecimals(6)
        self.V_setpoint_2.setMinimum(-1000000000.0)
        self.V_setpoint_2.setMaximum(10000004.0)
        self.V_setpoint_2.setSingleStep(10.0)
        self.V_setpoint_2.setProperty("value", 1.0)
        self.V_setpoint_2.setObjectName("V_setpoint_2")
        self.gridLayout.addWidget(self.V_setpoint_2, 7, 4, 1, 1)
        self.I_source_setpoint_3 = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.I_source_setpoint_3.setMinimumSize(QtCore.QSize(91, 0))
        self.I_source_setpoint_3.setAlignment(QtCore.Qt.AlignCenter)
        self.I_source_setpoint_3.setDecimals(1)
        self.I_source_setpoint_3.setMaximum(10000000.0)
        self.I_source_setpoint_3.setSingleStep(10.0)
        self.I_source_setpoint_3.setProperty("value", 100.0)
        self.I_source_setpoint_3.setObjectName("I_source_setpoint_3")
        self.gridLayout.addWidget(self.I_source_setpoint_3, 1, 7, 1, 1)
        self.B_z = QtGui.QLineEdit(self.groupBox_5)
        self.B_z.setEnabled(False)
        self.B_z.setFrame(True)
        self.B_z.setReadOnly(False)
        self.B_z.setObjectName("B_z")
        self.gridLayout.addWidget(self.B_z, 16, 7, 1, 1)
        self.B_Y_setpoint = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.B_Y_setpoint.setMinimumSize(QtCore.QSize(91, 0))
        self.B_Y_setpoint.setAlignment(QtCore.Qt.AlignCenter)
        self.B_Y_setpoint.setDecimals(4)
        self.B_Y_setpoint.setMinimum(-1.0)
        self.B_Y_setpoint.setMaximum(1.0)
        self.B_Y_setpoint.setSingleStep(0.1)
        self.B_Y_setpoint.setProperty("value", 0.0)
        self.B_Y_setpoint.setObjectName("B_Y_setpoint")
        self.gridLayout.addWidget(self.B_Y_setpoint, 13, 4, 1, 1)
        self.B_X_setpoint = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.B_X_setpoint.setMinimumSize(QtCore.QSize(91, 0))
        self.B_X_setpoint.setAlignment(QtCore.Qt.AlignCenter)
        self.B_X_setpoint.setDecimals(4)
        self.B_X_setpoint.setMinimum(-1.0)
        self.B_X_setpoint.setMaximum(1.0)
        self.B_X_setpoint.setSingleStep(0.1)
        self.B_X_setpoint.setProperty("value", 0.0)
        self.B_X_setpoint.setObjectName("B_X_setpoint")
        self.gridLayout.addWidget(self.B_X_setpoint, 13, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_5)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 10, 0, 2, 3)
        self.voltage_criterion_on = QtGui.QCheckBox(self.groupBox_5)
        self.voltage_criterion_on.setObjectName("voltage_criterion_on")
        self.gridLayout.addWidget(self.voltage_criterion_on, 8, 4, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_5)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 4, 2, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 7, 1, 1)
        self.B_Z_setpoint = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.B_Z_setpoint.setMinimumSize(QtCore.QSize(91, 0))
        self.B_Z_setpoint.setAlignment(QtCore.Qt.AlignCenter)
        self.B_Z_setpoint.setDecimals(4)
        self.B_Z_setpoint.setMinimum(-9.0)
        self.B_Z_setpoint.setMaximum(9.0)
        self.B_Z_setpoint.setSingleStep(0.5)
        self.B_Z_setpoint.setProperty("value", 0.0)
        self.B_Z_setpoint.setObjectName("B_Z_setpoint")
        self.gridLayout.addWidget(self.B_Z_setpoint, 13, 7, 1, 1)
        self.B_x = QtGui.QLineEdit(self.groupBox_5)
        self.B_x.setEnabled(False)
        self.B_x.setFrame(True)
        self.B_x.setReadOnly(False)
        self.B_x.setObjectName("B_x")
        self.gridLayout.addWidget(self.B_x, 16, 1, 1, 1)
        self.label_71 = QtGui.QLabel(self.groupBox_5)
        self.label_71.setAlignment(QtCore.Qt.AlignCenter)
        self.label_71.setObjectName("label_71")
        self.gridLayout.addWidget(self.label_71, 12, 7, 1, 1)
        self.label_73 = QtGui.QLabel(self.groupBox_5)
        self.label_73.setAlignment(QtCore.Qt.AlignCenter)
        self.label_73.setObjectName("label_73")
        self.gridLayout.addWidget(self.label_73, 12, 4, 1, 1)
        self.B_y = QtGui.QLineEdit(self.groupBox_5)
        self.B_y.setEnabled(False)
        self.B_y.setFrame(True)
        self.B_y.setReadOnly(False)
        self.B_y.setObjectName("B_y")
        self.gridLayout.addWidget(self.B_y, 16, 4, 1, 1)
        self.label_51 = QtGui.QLabel(self.groupBox_5)
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.gridLayout.addWidget(self.label_51, 12, 1, 1, 1)
        self.IV_voltage_criterion = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.IV_voltage_criterion.setMinimumSize(QtCore.QSize(91, 0))
        self.IV_voltage_criterion.setAlignment(QtCore.Qt.AlignCenter)
        self.IV_voltage_criterion.setDecimals(3)
        self.IV_voltage_criterion.setMaximum(100000000.0)
        self.IV_voltage_criterion.setSingleStep(10.0)
        self.IV_voltage_criterion.setProperty("value", 100.0)
        self.IV_voltage_criterion.setObjectName("IV_voltage_criterion")
        self.gridLayout.addWidget(self.IV_voltage_criterion, 9, 4, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 4, 1, 1)
        self.anglestart = QtGui.QDoubleSpinBox(self.tab)
        self.anglestart.setGeometry(QtCore.QRect(30, 710, 62, 22))
        self.anglestart.setMinimum(-1000.0)
        self.anglestart.setMaximum(1000.0)
        self.anglestart.setObjectName("anglestart")
        self.anglestop = QtGui.QDoubleSpinBox(self.tab)
        self.anglestop.setGeometry(QtCore.QRect(90, 710, 62, 22))
        self.anglestop.setMinimum(-1000.0)
        self.anglestop.setMaximum(1000.0)
        self.anglestop.setObjectName("anglestop")
        self.anglestep = QtGui.QDoubleSpinBox(self.tab)
        self.anglestep.setGeometry(QtCore.QRect(150, 710, 62, 22))
        self.anglestep.setMinimum(-1000.0)
        self.anglestep.setMaximum(1000.0)
        self.anglestep.setObjectName("anglestep")
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(30, 690, 46, 13))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(90, 690, 46, 13))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(150, 690, 46, 13))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(230, 710, 46, 13))
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Plot2D_1 = Plot2DDataWidget(self.tab_2)
        self.Plot2D_1.setObjectName("Plot2D_1")
        self.gridLayout_4.addWidget(self.Plot2D_1, 0, 0, 1, 1)
        self.Plot2D_2 = Plot2DDataWidget(self.tab_2)
        self.Plot2D_2.setObjectName("Plot2D_2")
        self.gridLayout_4.addWidget(self.Plot2D_2, 0, 1, 1, 1)
        self.Plot2D_3 = Plot2DDataWidget(self.tab_2)
        self.Plot2D_3.setObjectName("Plot2D_3")
        self.gridLayout_4.addWidget(self.Plot2D_3, 1, 0, 1, 1)
        self.Plot2D_4 = Plot2DDataWidget(self.tab_2)
        self.Plot2D_4.setObjectName("Plot2D_4")
        self.gridLayout_4.addWidget(self.Plot2D_4, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.instr_mdi = QtGui.QMdiArea(self.tab_6)
        self.instr_mdi.setFrameShape(QtGui.QFrame.Panel)
        self.instr_mdi.setFrameShadow(QtGui.QFrame.Plain)
        self.instr_mdi.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.instr_mdi.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.instr_mdi.setViewMode(QtGui.QMdiArea.SubWindowView)
        self.instr_mdi.setObjectName("instr_mdi")
        self.gridLayout_2.addWidget(self.instr_mdi, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        PyGMI.setCentralWidget(self.centralwidget)

        self.retranslateUi(PyGMI)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL("clicked()"), PyGMI.switch_measurements_state)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL("clicked()"), PyGMI.savefile_txt_input_open)
        QtCore.QObject.connect(self.pushButton_13, QtCore.SIGNAL("clicked()"), PyGMI.create_new_plotwidget)
        QtCore.QObject.connect(self.pushButton_14, QtCore.SIGNAL("clicked()"), PyGMI.create_config_menu)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL("clicked()"), PyGMI.update_list_of_meas_program)
        QtCore.QMetaObject.connectSlotsByName(PyGMI)
        PyGMI.setTabOrder(self.savefile_txt_input, self.pushButton)
        PyGMI.setTabOrder(self.pushButton, self.tabWidget)

    def retranslateUi(self, PyGMI):
        PyGMI.setWindowTitle(QtGui.QApplication.translate("PyGMI", "PyGMI v3.0 - Python Generic Measurements Interface", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("PyGMI", "Instr I/O", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("PyGMI", "E-mail alert address", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("PyGMI", "Single shot Measurements", None, QtGui.QApplication.UnicodeUTF8))
        self.measMode.setItemText(0, QtGui.QApplication.translate("PyGMI", "B Rem mode", None, QtGui.QApplication.UnicodeUTF8))
        self.measMode.setItemText(1, QtGui.QApplication.translate("PyGMI", "M vs H mode", None, QtGui.QApplication.UnicodeUTF8))
        self.measMode.setItemText(2, QtGui.QApplication.translate("PyGMI", "+I/-I mode", None, QtGui.QApplication.UnicodeUTF8))
        self.measMode.setItemText(3, QtGui.QApplication.translate("PyGMI", "M vs T mode", None, QtGui.QApplication.UnicodeUTF8))
        self.measMode.setItemText(4, QtGui.QApplication.translate("PyGMI", "IV curve (PC trigger)", None, QtGui.QApplication.UnicodeUTF8))
        self.measMode.setItemText(5, QtGui.QApplication.translate("PyGMI", "IV curve (T-link cable, not finished yet)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("PyGMI", "Measurements Program", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("PyGMI", "Start\n"
"Measurements", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("PyGMI", "Update\n"
"Program List", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("PyGMI", "Plots", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_13.setText(QtGui.QApplication.translate("PyGMI", "New Plot Window", None, QtGui.QApplication.UnicodeUTF8))
        self.NewPlotWindowTitle.setText(QtGui.QApplication.translate("PyGMI", "New Plot Window Title", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_14.setText(QtGui.QApplication.translate("PyGMI", "Config Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("PyGMI", "Macro Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("PyGMI", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.I_source_setpoint.setSuffix(QtGui.QApplication.translate("PyGMI", " µA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_68.setText(QtGui.QApplication.translate("PyGMI", "Current 2", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("PyGMI", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.mesure_speed.setSuffix(QtGui.QApplication.translate("PyGMI", " * 16.7 ms", None, QtGui.QApplication.UnicodeUTF8))
        self.I_source_setpoint_2.setSuffix(QtGui.QApplication.translate("PyGMI", " µA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("PyGMI", "Current persistent field", None, QtGui.QApplication.UnicodeUTF8))
        self.label_52.setText(QtGui.QApplication.translate("PyGMI", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.repeat_points.setSuffix(QtGui.QApplication.translate("PyGMI", " times", None, QtGui.QApplication.UnicodeUTF8))
        self.savefile_txt_input.setText(QtGui.QApplication.translate("PyGMI", "measurements data/default.txt", None, QtGui.QApplication.UnicodeUTF8))
        self.label_77.setText(QtGui.QApplication.translate("PyGMI", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_78.setText(QtGui.QApplication.translate("PyGMI", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.V_setpoint_1.setSuffix(QtGui.QApplication.translate("PyGMI", " V", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("PyGMI", "Current 1", None, QtGui.QApplication.UnicodeUTF8))
        self.V_setpoint_3.setSuffix(QtGui.QApplication.translate("PyGMI", " V", None, QtGui.QApplication.UnicodeUTF8))
        self.mesure_delay.setSuffix(QtGui.QApplication.translate("PyGMI", " ms", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("PyGMI", "Save file :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_56.setText(QtGui.QApplication.translate("PyGMI", "Voltage 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_69.setText(QtGui.QApplication.translate("PyGMI", "Current 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_81.setText(QtGui.QApplication.translate("PyGMI", "Voltage 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_82.setText(QtGui.QApplication.translate("PyGMI", "Voltage 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_70.setText(QtGui.QApplication.translate("PyGMI", "Measurements speed", None, QtGui.QApplication.UnicodeUTF8))
        self.V_setpoint_2.setSuffix(QtGui.QApplication.translate("PyGMI", " V", None, QtGui.QApplication.UnicodeUTF8))
        self.I_source_setpoint_3.setSuffix(QtGui.QApplication.translate("PyGMI", " µA", None, QtGui.QApplication.UnicodeUTF8))
        self.B_Y_setpoint.setSuffix(QtGui.QApplication.translate("PyGMI", " T", None, QtGui.QApplication.UnicodeUTF8))
        self.B_X_setpoint.setSuffix(QtGui.QApplication.translate("PyGMI", " T", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("PyGMI", "Target field", None, QtGui.QApplication.UnicodeUTF8))
        self.voltage_criterion_on.setText(QtGui.QApplication.translate("PyGMI", "Voltage criterion", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("PyGMI", "Time between \n"
" measurements cycles", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("PyGMI", "Repeat each point", None, QtGui.QApplication.UnicodeUTF8))
        self.B_Z_setpoint.setSuffix(QtGui.QApplication.translate("PyGMI", " T", None, QtGui.QApplication.UnicodeUTF8))
        self.label_71.setText(QtGui.QApplication.translate("PyGMI", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_73.setText(QtGui.QApplication.translate("PyGMI", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("PyGMI", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.IV_voltage_criterion.setSuffix(QtGui.QApplication.translate("PyGMI", " µV", None, QtGui.QApplication.UnicodeUTF8))
        self.anglestart.setSuffix(QtGui.QApplication.translate("PyGMI", " °", None, QtGui.QApplication.UnicodeUTF8))
        self.anglestop.setSuffix(QtGui.QApplication.translate("PyGMI", " °", None, QtGui.QApplication.UnicodeUTF8))
        self.anglestep.setSuffix(QtGui.QApplication.translate("PyGMI", " °", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("PyGMI", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("PyGMI", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("PyGMI", "Step", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("PyGMI", "Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("PyGMI", "Measurements", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("PyGMI", "Detailed Graphs", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("PyGMI", "Instruments panel", None, QtGui.QApplication.UnicodeUTF8))

from Macro_editor import Macro_editor
from Plot2DDataWidget import Plot2DDataWidget
from Instruments_connection import Instruments_connection
