# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\msdguest\Documents\Programmation latest projects\PyGMI\PyGMI\PyGMI-release - v3.0 beta - WIP\PyGMI_files\Instruments_connection.ui'
#
# Created: Mon May 18 12:16:47 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Instruments_connection(object):
    def setupUi(self, Instruments_connection):
        Instruments_connection.setObjectName("Instruments_connection")
        Instruments_connection.resize(1086, 762)
        self.gridLayout_5 = QtGui.QGridLayout(Instruments_connection)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_11 = QtGui.QLabel(Instruments_connection)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 0, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_12 = QtGui.QLabel(Instruments_connection)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 1, 1, 1, 1)
        self.label_42 = QtGui.QLabel(Instruments_connection)
        self.label_42.setCursor(QtCore.Qt.IBeamCursor)
        self.label_42.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.label_42.setText("")
        self.label_42.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_42.setObjectName("label_42")
        self.gridLayout_3.addWidget(self.label_42, 1, 2, 1, 2)
        self.instr_on_1 = QtGui.QCheckBox(Instruments_connection)
        self.instr_on_1.setText("")
        self.instr_on_1.setChecked(True)
        self.instr_on_1.setObjectName("instr_on_1")
        self.gridLayout_3.addWidget(self.instr_on_1, 2, 0, 1, 1)
        self.instr_visa_address_1 = QtGui.QLineEdit(Instruments_connection)
        self.instr_visa_address_1.setObjectName("instr_visa_address_1")
        self.gridLayout_3.addWidget(self.instr_visa_address_1, 2, 1, 1, 2)
        self.instr_instrtype_1 = QtGui.QComboBox(Instruments_connection)
        self.instr_instrtype_1.setObjectName("instr_instrtype_1")
        self.gridLayout_3.addWidget(self.instr_instrtype_1, 2, 3, 1, 1)
        self.label_13 = QtGui.QLabel(Instruments_connection)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 3, 1, 1, 1)
        self.label_43 = QtGui.QLabel(Instruments_connection)
        self.label_43.setCursor(QtCore.Qt.IBeamCursor)
        self.label_43.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.label_43.setText("")
        self.label_43.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_43.setObjectName("label_43")
        self.gridLayout_3.addWidget(self.label_43, 3, 2, 1, 2)
        self.instr_on_2 = QtGui.QCheckBox(Instruments_connection)
        self.instr_on_2.setText("")
        self.instr_on_2.setChecked(False)
        self.instr_on_2.setObjectName("instr_on_2")
        self.gridLayout_3.addWidget(self.instr_on_2, 4, 0, 1, 1)
        self.instr_visa_address_2 = QtGui.QLineEdit(Instruments_connection)
        self.instr_visa_address_2.setObjectName("instr_visa_address_2")
        self.gridLayout_3.addWidget(self.instr_visa_address_2, 4, 1, 1, 2)
        self.instr_instrtype_2 = QtGui.QComboBox(Instruments_connection)
        self.instr_instrtype_2.setObjectName("instr_instrtype_2")
        self.gridLayout_3.addWidget(self.instr_instrtype_2, 4, 3, 1, 1)
        self.label_16 = QtGui.QLabel(Instruments_connection)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 5, 1, 1, 1)
        self.label_48 = QtGui.QLabel(Instruments_connection)
        self.label_48.setCursor(QtCore.Qt.IBeamCursor)
        self.label_48.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.label_48.setText("")
        self.label_48.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_48.setObjectName("label_48")
        self.gridLayout_3.addWidget(self.label_48, 5, 2, 1, 2)
        self.instr_on_3 = QtGui.QCheckBox(Instruments_connection)
        self.instr_on_3.setText("")
        self.instr_on_3.setChecked(False)
        self.instr_on_3.setObjectName("instr_on_3")
        self.gridLayout_3.addWidget(self.instr_on_3, 6, 0, 1, 1)
        self.instr_visa_address_3 = QtGui.QLineEdit(Instruments_connection)
        self.instr_visa_address_3.setObjectName("instr_visa_address_3")
        self.gridLayout_3.addWidget(self.instr_visa_address_3, 6, 1, 1, 2)
        self.instr_instrtype_3 = QtGui.QComboBox(Instruments_connection)
        self.instr_instrtype_3.setObjectName("instr_instrtype_3")
        self.gridLayout_3.addWidget(self.instr_instrtype_3, 6, 3, 1, 1)
        self.label_21 = QtGui.QLabel(Instruments_connection)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 7, 1, 1, 1)
        self.label_51 = QtGui.QLabel(Instruments_connection)
        self.label_51.setCursor(QtCore.Qt.IBeamCursor)
        self.label_51.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.label_51.setText("")
        self.label_51.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_51.setObjectName("label_51")
        self.gridLayout_3.addWidget(self.label_51, 7, 2, 1, 2)
        self.instr_on_4 = QtGui.QCheckBox(Instruments_connection)
        self.instr_on_4.setText("")
        self.instr_on_4.setChecked(False)
        self.instr_on_4.setObjectName("instr_on_4")
        self.gridLayout_3.addWidget(self.instr_on_4, 8, 0, 1, 1)
        self.instr_visa_address_4 = QtGui.QLineEdit(Instruments_connection)
        self.instr_visa_address_4.setObjectName("instr_visa_address_4")
        self.gridLayout_3.addWidget(self.instr_visa_address_4, 8, 1, 1, 2)
        self.instr_instrtype_4 = QtGui.QComboBox(Instruments_connection)
        self.instr_instrtype_4.setObjectName("instr_instrtype_4")
        self.gridLayout_3.addWidget(self.instr_instrtype_4, 8, 3, 1, 1)
        self.label_22 = QtGui.QLabel(Instruments_connection)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 9, 1, 1, 1)
        self.label_60 = QtGui.QLabel(Instruments_connection)
        self.label_60.setCursor(QtCore.Qt.IBeamCursor)
        self.label_60.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.label_60.setText("")
        self.label_60.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_60.setObjectName("label_60")
        self.gridLayout_3.addWidget(self.label_60, 9, 2, 1, 2)
        self.instr_on_5 = QtGui.QCheckBox(Instruments_connection)
        self.instr_on_5.setText("")
        self.instr_on_5.setChecked(False)
        self.instr_on_5.setObjectName("instr_on_5")
        self.gridLayout_3.addWidget(self.instr_on_5, 10, 0, 1, 1)
        self.instr_visa_address_5 = QtGui.QLineEdit(Instruments_connection)
        self.instr_visa_address_5.setObjectName("instr_visa_address_5")
        self.gridLayout_3.addWidget(self.instr_visa_address_5, 10, 1, 1, 2)
        self.instr_instrtype_5 = QtGui.QComboBox(Instruments_connection)
        self.instr_instrtype_5.setObjectName("instr_instrtype_5")
        self.gridLayout_3.addWidget(self.instr_instrtype_5, 10, 3, 1, 1)
        self.label_35 = QtGui.QLabel(Instruments_connection)
        self.label_35.setObjectName("label_35")
        self.gridLayout_3.addWidget(self.label_35, 11, 1, 1, 1)
        self.label_61 = QtGui.QLabel(Instruments_connection)
        self.label_61.setCursor(QtCore.Qt.IBeamCursor)
        self.label_61.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.label_61.setText("")
        self.label_61.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_61.setObjectName("label_61")
        self.gridLayout_3.addWidget(self.label_61, 11, 2, 1, 2)
        self.instr_on_6 = QtGui.QCheckBox(Instruments_connection)
        self.instr_on_6.setText("")
        self.instr_on_6.setChecked(False)
        self.instr_on_6.setObjectName("instr_on_6")
        self.gridLayout_3.addWidget(self.instr_on_6, 12, 0, 1, 1)
        self.instr_visa_address_6 = QtGui.QLineEdit(Instruments_connection)
        self.instr_visa_address_6.setObjectName("instr_visa_address_6")
        self.gridLayout_3.addWidget(self.instr_visa_address_6, 12, 1, 1, 2)
        self.instr_instrtype_6 = QtGui.QComboBox(Instruments_connection)
        self.instr_instrtype_6.setObjectName("instr_instrtype_6")
        self.gridLayout_3.addWidget(self.instr_instrtype_6, 12, 3, 1, 1)
        self.label_36 = QtGui.QLabel(Instruments_connection)
        self.label_36.setObjectName("label_36")
        self.gridLayout_3.addWidget(self.label_36, 13, 1, 1, 1)
        self.label_62 = QtGui.QLabel(Instruments_connection)
        self.label_62.setCursor(QtCore.Qt.IBeamCursor)
        self.label_62.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.label_62.setText("")
        self.label_62.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_62.setObjectName("label_62")
        self.gridLayout_3.addWidget(self.label_62, 13, 2, 1, 2)
        self.instr_on_7 = QtGui.QCheckBox(Instruments_connection)
        self.instr_on_7.setText("")
        self.instr_on_7.setChecked(False)
        self.instr_on_7.setObjectName("instr_on_7")
        self.gridLayout_3.addWidget(self.instr_on_7, 14, 0, 1, 1)
        self.instr_visa_address_7 = QtGui.QLineEdit(Instruments_connection)
        self.instr_visa_address_7.setObjectName("instr_visa_address_7")
        self.gridLayout_3.addWidget(self.instr_visa_address_7, 14, 1, 1, 2)
        self.instr_instrtype_7 = QtGui.QComboBox(Instruments_connection)
        self.instr_instrtype_7.setObjectName("instr_instrtype_7")
        self.gridLayout_3.addWidget(self.instr_instrtype_7, 14, 3, 1, 1)
        self.label_37 = QtGui.QLabel(Instruments_connection)
        self.label_37.setObjectName("label_37")
        self.gridLayout_3.addWidget(self.label_37, 15, 1, 1, 1)
        self.label_63 = QtGui.QLabel(Instruments_connection)
        self.label_63.setCursor(QtCore.Qt.IBeamCursor)
        self.label_63.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.label_63.setText("")
        self.label_63.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_63.setObjectName("label_63")
        self.gridLayout_3.addWidget(self.label_63, 15, 2, 1, 2)
        self.instr_on_8 = QtGui.QCheckBox(Instruments_connection)
        self.instr_on_8.setText("")
        self.instr_on_8.setChecked(False)
        self.instr_on_8.setObjectName("instr_on_8")
        self.gridLayout_3.addWidget(self.instr_on_8, 16, 0, 1, 1)
        self.instr_visa_address_8 = QtGui.QLineEdit(Instruments_connection)
        self.instr_visa_address_8.setObjectName("instr_visa_address_8")
        self.gridLayout_3.addWidget(self.instr_visa_address_8, 16, 1, 1, 2)
        self.instr_instrtype_8 = QtGui.QComboBox(Instruments_connection)
        self.instr_instrtype_8.setObjectName("instr_instrtype_8")
        self.gridLayout_3.addWidget(self.instr_instrtype_8, 16, 3, 1, 1)
        self.label_38 = QtGui.QLabel(Instruments_connection)
        self.label_38.setObjectName("label_38")
        self.gridLayout_3.addWidget(self.label_38, 17, 1, 1, 1)
        self.label_64 = QtGui.QLabel(Instruments_connection)
        self.label_64.setCursor(QtCore.Qt.IBeamCursor)
        self.label_64.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.label_64.setText("")
        self.label_64.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_64.setObjectName("label_64")
        self.gridLayout_3.addWidget(self.label_64, 17, 2, 1, 2)
        self.instr_on_9 = QtGui.QCheckBox(Instruments_connection)
        self.instr_on_9.setText("")
        self.instr_on_9.setChecked(False)
        self.instr_on_9.setObjectName("instr_on_9")
        self.gridLayout_3.addWidget(self.instr_on_9, 18, 0, 1, 1)
        self.instr_visa_address_9 = QtGui.QLineEdit(Instruments_connection)
        self.instr_visa_address_9.setObjectName("instr_visa_address_9")
        self.gridLayout_3.addWidget(self.instr_visa_address_9, 18, 1, 1, 2)
        self.instr_instrtype_9 = QtGui.QComboBox(Instruments_connection)
        self.instr_instrtype_9.setObjectName("instr_instrtype_9")
        self.gridLayout_3.addWidget(self.instr_instrtype_9, 18, 3, 1, 1)
        self.label_15 = QtGui.QLabel(Instruments_connection)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 0, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(2, 2)
        self.gridLayout_3.setColumnStretch(3, 2)
        self.gridLayout_5.addLayout(self.gridLayout_3, 3, 0, 13, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout_4.setHorizontalSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.temp_controller_on = QtGui.QCheckBox(Instruments_connection)
        self.temp_controller_on.setText("")
        self.temp_controller_on.setChecked(True)
        self.temp_controller_on.setObjectName("temp_controller_on")
        self.gridLayout_4.addWidget(self.temp_controller_on, 1, 0, 1, 1)
        self.temp_controller_visa_address = QtGui.QLineEdit(Instruments_connection)
        self.temp_controller_visa_address.setObjectName("temp_controller_visa_address")
        self.gridLayout_4.addWidget(self.temp_controller_visa_address, 1, 1, 1, 2)
        self.temp_controller_instrtype = QtGui.QComboBox(Instruments_connection)
        self.temp_controller_instrtype.setObjectName("temp_controller_instrtype")
        self.gridLayout_4.addWidget(self.temp_controller_instrtype, 1, 3, 1, 1)
        self.label_34 = QtGui.QLabel(Instruments_connection)
        self.label_34.setObjectName("label_34")
        self.gridLayout_4.addWidget(self.label_34, 2, 1, 1, 3)
        self.magnet_X_on = QtGui.QCheckBox(Instruments_connection)
        self.magnet_X_on.setText("")
        self.magnet_X_on.setChecked(False)
        self.magnet_X_on.setObjectName("magnet_X_on")
        self.gridLayout_4.addWidget(self.magnet_X_on, 3, 0, 1, 1)
        self.magnet_X_visa_address = QtGui.QLineEdit(Instruments_connection)
        self.magnet_X_visa_address.setObjectName("magnet_X_visa_address")
        self.gridLayout_4.addWidget(self.magnet_X_visa_address, 3, 1, 1, 2)
        self.magnet_X_instrtype = QtGui.QComboBox(Instruments_connection)
        self.magnet_X_instrtype.setObjectName("magnet_X_instrtype")
        self.gridLayout_4.addWidget(self.magnet_X_instrtype, 3, 3, 1, 1)
        self.label_33 = QtGui.QLabel(Instruments_connection)
        self.label_33.setObjectName("label_33")
        self.gridLayout_4.addWidget(self.label_33, 4, 1, 1, 3)
        self.magnet_Y_on = QtGui.QCheckBox(Instruments_connection)
        self.magnet_Y_on.setText("")
        self.magnet_Y_on.setChecked(False)
        self.magnet_Y_on.setObjectName("magnet_Y_on")
        self.gridLayout_4.addWidget(self.magnet_Y_on, 5, 0, 1, 1)
        self.magnet_Y_visa_address = QtGui.QLineEdit(Instruments_connection)
        self.magnet_Y_visa_address.setObjectName("magnet_Y_visa_address")
        self.gridLayout_4.addWidget(self.magnet_Y_visa_address, 5, 1, 1, 2)
        self.magnet_Y_instrtype = QtGui.QComboBox(Instruments_connection)
        self.magnet_Y_instrtype.setObjectName("magnet_Y_instrtype")
        self.gridLayout_4.addWidget(self.magnet_Y_instrtype, 5, 3, 1, 1)
        self.label_18 = QtGui.QLabel(Instruments_connection)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 6, 1, 1, 3)
        self.magnet_Z_on = QtGui.QCheckBox(Instruments_connection)
        self.magnet_Z_on.setText("")
        self.magnet_Z_on.setChecked(True)
        self.magnet_Z_on.setObjectName("magnet_Z_on")
        self.gridLayout_4.addWidget(self.magnet_Z_on, 7, 0, 1, 1)
        self.magnet_Z_visa_address = QtGui.QLineEdit(Instruments_connection)
        self.magnet_Z_visa_address.setObjectName("magnet_Z_visa_address")
        self.gridLayout_4.addWidget(self.magnet_Z_visa_address, 7, 1, 1, 2)
        self.magnet_Z_instrtype = QtGui.QComboBox(Instruments_connection)
        self.magnet_Z_instrtype.setObjectName("magnet_Z_instrtype")
        self.gridLayout_4.addWidget(self.magnet_Z_instrtype, 7, 3, 1, 1)
        self.label_73 = QtGui.QLabel(Instruments_connection)
        self.label_73.setObjectName("label_73")
        self.gridLayout_4.addWidget(self.label_73, 8, 1, 1, 1)
        self.label_74 = QtGui.QLabel(Instruments_connection)
        self.label_74.setCursor(QtCore.Qt.IBeamCursor)
        self.label_74.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.label_74.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_74.setObjectName("label_74")
        self.gridLayout_4.addWidget(self.label_74, 8, 2, 1, 2)
        self.instr_on_14 = QtGui.QCheckBox(Instruments_connection)
        self.instr_on_14.setText("")
        self.instr_on_14.setChecked(True)
        self.instr_on_14.setObjectName("instr_on_14")
        self.gridLayout_4.addWidget(self.instr_on_14, 9, 0, 1, 1)
        self.instr_visa_address_14 = QtGui.QLineEdit(Instruments_connection)
        self.instr_visa_address_14.setObjectName("instr_visa_address_14")
        self.gridLayout_4.addWidget(self.instr_visa_address_14, 9, 1, 1, 2)
        self.instr_instrtype_14 = QtGui.QComboBox(Instruments_connection)
        self.instr_instrtype_14.setObjectName("instr_instrtype_14")
        self.gridLayout_4.addWidget(self.instr_instrtype_14, 9, 3, 1, 1)
        self.label_39 = QtGui.QLabel(Instruments_connection)
        self.label_39.setObjectName("label_39")
        self.gridLayout_4.addWidget(self.label_39, 10, 1, 1, 1)
        self.label_65 = QtGui.QLabel(Instruments_connection)
        self.label_65.setCursor(QtCore.Qt.IBeamCursor)
        self.label_65.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.label_65.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_65.setObjectName("label_65")
        self.gridLayout_4.addWidget(self.label_65, 10, 2, 1, 2)
        self.instr_on_10 = QtGui.QCheckBox(Instruments_connection)
        self.instr_on_10.setText("")
        self.instr_on_10.setChecked(True)
        self.instr_on_10.setObjectName("instr_on_10")
        self.gridLayout_4.addWidget(self.instr_on_10, 11, 0, 1, 1)
        self.instr_visa_address_10 = QtGui.QLineEdit(Instruments_connection)
        self.instr_visa_address_10.setObjectName("instr_visa_address_10")
        self.gridLayout_4.addWidget(self.instr_visa_address_10, 11, 1, 1, 2)
        self.instr_instrtype_10 = QtGui.QComboBox(Instruments_connection)
        self.instr_instrtype_10.setObjectName("instr_instrtype_10")
        self.gridLayout_4.addWidget(self.instr_instrtype_10, 11, 3, 1, 1)
        self.label_40 = QtGui.QLabel(Instruments_connection)
        self.label_40.setObjectName("label_40")
        self.gridLayout_4.addWidget(self.label_40, 12, 1, 1, 1)
        self.label_66 = QtGui.QLabel(Instruments_connection)
        self.label_66.setCursor(QtCore.Qt.IBeamCursor)
        self.label_66.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.label_66.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_66.setObjectName("label_66")
        self.gridLayout_4.addWidget(self.label_66, 12, 2, 1, 2)
        self.instr_on_11 = QtGui.QCheckBox(Instruments_connection)
        self.instr_on_11.setText("")
        self.instr_on_11.setChecked(True)
        self.instr_on_11.setObjectName("instr_on_11")
        self.gridLayout_4.addWidget(self.instr_on_11, 13, 0, 1, 1)
        self.instr_visa_address_11 = QtGui.QLineEdit(Instruments_connection)
        self.instr_visa_address_11.setObjectName("instr_visa_address_11")
        self.gridLayout_4.addWidget(self.instr_visa_address_11, 13, 1, 1, 2)
        self.instr_instrtype_11 = QtGui.QComboBox(Instruments_connection)
        self.instr_instrtype_11.setObjectName("instr_instrtype_11")
        self.gridLayout_4.addWidget(self.instr_instrtype_11, 13, 3, 1, 1)
        self.label_41 = QtGui.QLabel(Instruments_connection)
        self.label_41.setObjectName("label_41")
        self.gridLayout_4.addWidget(self.label_41, 14, 1, 1, 1)
        self.label_67 = QtGui.QLabel(Instruments_connection)
        self.label_67.setCursor(QtCore.Qt.IBeamCursor)
        self.label_67.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.label_67.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_67.setObjectName("label_67")
        self.gridLayout_4.addWidget(self.label_67, 14, 2, 1, 2)
        self.instr_on_12 = QtGui.QCheckBox(Instruments_connection)
        self.instr_on_12.setText("")
        self.instr_on_12.setChecked(True)
        self.instr_on_12.setObjectName("instr_on_12")
        self.gridLayout_4.addWidget(self.instr_on_12, 15, 0, 1, 1)
        self.instr_visa_address_12 = QtGui.QLineEdit(Instruments_connection)
        self.instr_visa_address_12.setObjectName("instr_visa_address_12")
        self.gridLayout_4.addWidget(self.instr_visa_address_12, 15, 1, 1, 2)
        self.instr_instrtype_12 = QtGui.QComboBox(Instruments_connection)
        self.instr_instrtype_12.setObjectName("instr_instrtype_12")
        self.gridLayout_4.addWidget(self.instr_instrtype_12, 15, 3, 1, 1)
        self.label_14 = QtGui.QLabel(Instruments_connection)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 0, 1, 1, 3)
        self.gridLayout_4.setColumnStretch(2, 2)
        self.gridLayout_4.setColumnStretch(3, 2)
        self.gridLayout_5.addLayout(self.gridLayout_4, 3, 1, 13, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.instr_table = QtGui.QTableWidget(Instruments_connection)
        self.instr_table.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.instr_table.sizePolicy().hasHeightForWidth())
        self.instr_table.setSizePolicy(sizePolicy)
        self.instr_table.setObjectName("instr_table")
        self.instr_table.setColumnCount(2)
        self.instr_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.instr_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.instr_table.setHorizontalHeaderItem(1, item)
        self.instr_table.horizontalHeader().setDefaultSectionSize(350)
        self.instr_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.instr_table, 0, 0, 6, 1)
        self.pushButton_instr = QtGui.QPushButton(Instruments_connection)
        self.pushButton_instr.setObjectName("pushButton_instr")
        self.gridLayout.addWidget(self.pushButton_instr, 0, 1, 1, 1)
        self.pushButton_instr_2 = QtGui.QPushButton(Instruments_connection)
        self.pushButton_instr_2.setObjectName("pushButton_instr_2")
        self.gridLayout.addWidget(self.pushButton_instr_2, 1, 1, 1, 1)
        self.pushButton_instr_5 = QtGui.QPushButton(Instruments_connection)
        self.pushButton_instr_5.setObjectName("pushButton_instr_5")
        self.gridLayout.addWidget(self.pushButton_instr_5, 4, 1, 1, 1)
        self.pushButton_instr_6 = QtGui.QPushButton(Instruments_connection)
        self.pushButton_instr_6.setObjectName("pushButton_instr_6")
        self.gridLayout.addWidget(self.pushButton_instr_6, 5, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 1, 0, 1, 3)
        self.groupBox_2 = QtGui.QGroupBox(Instruments_connection)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(370, 200))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_32 = QtGui.QLabel(self.groupBox_2)
        self.label_32.setGeometry(QtCore.QRect(10, 20, 421, 20))
        self.label_32.setObjectName("label_32")
        self.channels_list_1 = QtGui.QLineEdit(self.groupBox_2)
        self.channels_list_1.setGeometry(QtCore.QRect(10, 40, 351, 20))
        self.channels_list_1.setObjectName("channels_list_1")
        self.label_71 = QtGui.QLabel(self.groupBox_2)
        self.label_71.setGeometry(QtCore.QRect(10, 70, 442, 13))
        self.label_71.setObjectName("label_71")
        self.channels_list_2 = QtGui.QLineEdit(self.groupBox_2)
        self.channels_list_2.setGeometry(QtCore.QRect(10, 90, 351, 20))
        self.channels_list_2.setObjectName("channels_list_2")
        self.mapping = QtGui.QLineEdit(self.groupBox_2)
        self.mapping.setGeometry(QtCore.QRect(10, 140, 351, 20))
        self.mapping.setObjectName("mapping")
        self.label_77 = QtGui.QLabel(self.groupBox_2)
        self.label_77.setGeometry(QtCore.QRect(10, 120, 442, 13))
        self.label_77.setObjectName("label_77")
        self.gridLayout_5.addWidget(self.groupBox_2, 3, 2, 1, 1)
        self.groupBox = QtGui.QGroupBox(Instruments_connection)
        self.groupBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 250))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.testanswer = QtGui.QTextEdit(self.groupBox)
        self.testanswer.setGeometry(QtCore.QRect(10, 140, 261, 100))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testanswer.sizePolicy().hasHeightForWidth())
        self.testanswer.setSizePolicy(sizePolicy)
        self.testanswer.setMaximumSize(QtCore.QSize(16777215, 100))
        self.testanswer.setObjectName("testanswer")
        self.label_76 = QtGui.QLabel(self.groupBox)
        self.label_76.setGeometry(QtCore.QRect(10, 120, 383, 13))
        self.label_76.setObjectName("label_76")
        self.label_72 = QtGui.QLabel(self.groupBox)
        self.label_72.setGeometry(QtCore.QRect(10, 20, 383, 13))
        self.label_72.setObjectName("label_72")
        self.label_75 = QtGui.QLabel(self.groupBox)
        self.label_75.setGeometry(QtCore.QRect(10, 68, 383, 13))
        self.label_75.setObjectName("label_75")
        self.testinst = QtGui.QLineEdit(self.groupBox)
        self.testinst.setGeometry(QtCore.QRect(10, 90, 261, 20))
        self.testinst.setObjectName("testinst")
        self.testcommand = QtGui.QLineEdit(self.groupBox)
        self.testcommand.setGeometry(QtCore.QRect(10, 40, 261, 20))
        self.testcommand.setObjectName("testcommand")
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(280, 20, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtGui.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 50, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtGui.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 140, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_5.addWidget(self.groupBox, 4, 2, 1, 1)

        self.retranslateUi(Instruments_connection)
        QtCore.QObject.connect(self.pushButton_instr_2, QtCore.SIGNAL("clicked()"), Instruments_connection.init_instr)
        QtCore.QObject.connect(self.pushButton_instr, QtCore.SIGNAL("clicked()"), Instruments_connection.refresh_instr_list)
        QtCore.QObject.connect(self.pushButton_instr_5, QtCore.SIGNAL("clicked()"), Instruments_connection.saveInstrconf)
        QtCore.QObject.connect(self.pushButton_instr_6, QtCore.SIGNAL("clicked()"), Instruments_connection.loadInstrconf)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL("clicked()"), Instruments_connection.write2inst)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL("clicked()"), Instruments_connection.ask2inst)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL("clicked()"), Instruments_connection.readinst)
        QtCore.QMetaObject.connectSlotsByName(Instruments_connection)

    def retranslateUi(self, Instruments_connection):
        Instruments_connection.setWindowTitle(QtGui.QApplication.translate("Instruments_connection", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Instruments_connection", "List of Instruments", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Instruments_connection", "Instr1", None, QtGui.QApplication.UnicodeUTF8))
        self.instr_visa_address_1.setText(QtGui.QApplication.translate("Instruments_connection", "GPIB1::9", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Instruments_connection", "Instr2", None, QtGui.QApplication.UnicodeUTF8))
        self.instr_visa_address_2.setText(QtGui.QApplication.translate("Instruments_connection", "GPIB1::7", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Instruments_connection", "Instr3", None, QtGui.QApplication.UnicodeUTF8))
        self.instr_visa_address_3.setText(QtGui.QApplication.translate("Instruments_connection", "GPIB1::1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Instruments_connection", "Instr4", None, QtGui.QApplication.UnicodeUTF8))
        self.instr_visa_address_4.setText(QtGui.QApplication.translate("Instruments_connection", "GPIB1::11", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Instruments_connection", "Instr5", None, QtGui.QApplication.UnicodeUTF8))
        self.instr_visa_address_5.setText(QtGui.QApplication.translate("Instruments_connection", "GPIB1::14", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("Instruments_connection", "Instr6", None, QtGui.QApplication.UnicodeUTF8))
        self.instr_visa_address_6.setText(QtGui.QApplication.translate("Instruments_connection", "GPIB1::18", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("Instruments_connection", "Instr7", None, QtGui.QApplication.UnicodeUTF8))
        self.instr_visa_address_7.setText(QtGui.QApplication.translate("Instruments_connection", "GPIB1::10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("Instruments_connection", "Instr8", None, QtGui.QApplication.UnicodeUTF8))
        self.instr_visa_address_8.setText(QtGui.QApplication.translate("Instruments_connection", "GPIB1::30", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("Instruments_connection", "Instr9", None, QtGui.QApplication.UnicodeUTF8))
        self.instr_visa_address_9.setText(QtGui.QApplication.translate("Instruments_connection", "GPIB1::30", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Instruments_connection", "Visa Addresses", None, QtGui.QApplication.UnicodeUTF8))
        self.temp_controller_visa_address.setText(QtGui.QApplication.translate("Instruments_connection", "ID12_LS340_Temp_Controller", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("Instruments_connection", "Magnet power supply X - axis", None, QtGui.QApplication.UnicodeUTF8))
        self.magnet_X_visa_address.setText(QtGui.QApplication.translate("Instruments_connection", "AMI420_X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("Instruments_connection", "Magnet power supply Y - axis", None, QtGui.QApplication.UnicodeUTF8))
        self.magnet_Y_visa_address.setText(QtGui.QApplication.translate("Instruments_connection", "AMI420_Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Instruments_connection", "Magnet power supply Z - axis", None, QtGui.QApplication.UnicodeUTF8))
        self.magnet_Z_visa_address.setText(QtGui.QApplication.translate("Instruments_connection", "ID22_AMI420_magnet", None, QtGui.QApplication.UnicodeUTF8))
        self.label_73.setText(QtGui.QApplication.translate("Instruments_connection", "Instr14", None, QtGui.QApplication.UnicodeUTF8))
        self.label_74.setText(QtGui.QApplication.translate("Instruments_connection", "LHe Level", None, QtGui.QApplication.UnicodeUTF8))
        self.instr_visa_address_14.setText(QtGui.QApplication.translate("Instruments_connection", "GPIB1::1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("Instruments_connection", "Instr10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_65.setText(QtGui.QApplication.translate("Instruments_connection", " Current source", None, QtGui.QApplication.UnicodeUTF8))
        self.instr_visa_address_10.setText(QtGui.QApplication.translate("Instruments_connection", "GPIB1::19", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("Instruments_connection", "Instr11", None, QtGui.QApplication.UnicodeUTF8))
        self.label_66.setText(QtGui.QApplication.translate("Instruments_connection", "rotator", None, QtGui.QApplication.UnicodeUTF8))
        self.instr_visa_address_11.setText(QtGui.QApplication.translate("Instruments_connection", "COM8", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("Instruments_connection", "Instr12", None, QtGui.QApplication.UnicodeUTF8))
        self.label_67.setText(QtGui.QApplication.translate("Instruments_connection", "BNC switch", None, QtGui.QApplication.UnicodeUTF8))
        self.instr_visa_address_12.setText(QtGui.QApplication.translate("Instruments_connection", "COM9", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Instruments_connection", "Temperature Controller", None, QtGui.QApplication.UnicodeUTF8))
        self.instr_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Instruments_connection", "Instrument Name", None, QtGui.QApplication.UnicodeUTF8))
        self.instr_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Instruments_connection", "Visa Address", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_instr.setText(QtGui.QApplication.translate("Instruments_connection", "Scan for\n"
"Instruments", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_instr_2.setText(QtGui.QApplication.translate("Instruments_connection", "Initialize\n"
"Instruments", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_instr_5.setText(QtGui.QApplication.translate("Instruments_connection", "Save\n"
"Instruments configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_instr_6.setText(QtGui.QApplication.translate("Instruments_connection", "Load\n"
"Instruments configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Instruments_connection", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("Instruments_connection", "Active channels - list 1", None, QtGui.QApplication.UnicodeUTF8))
        self.channels_list_1.setText(QtGui.QApplication.translate("Instruments_connection", "A,B", None, QtGui.QApplication.UnicodeUTF8))
        self.label_71.setText(QtGui.QApplication.translate("Instruments_connection", "Active channels - list 2", None, QtGui.QApplication.UnicodeUTF8))
        self.channels_list_2.setText(QtGui.QApplication.translate("Instruments_connection", "A,B,C", None, QtGui.QApplication.UnicodeUTF8))
        self.mapping.setText(QtGui.QApplication.translate("Instruments_connection", "A:1,B:2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_77.setText(QtGui.QApplication.translate("Instruments_connection", "Mapping", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Instruments_connection", "Instruments testing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_76.setText(QtGui.QApplication.translate("Instruments_connection", "Answer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_72.setText(QtGui.QApplication.translate("Instruments_connection", "Send command", None, QtGui.QApplication.UnicodeUTF8))
        self.label_75.setText(QtGui.QApplication.translate("Instruments_connection", "To", None, QtGui.QApplication.UnicodeUTF8))
        self.testinst.setText(QtGui.QApplication.translate("Instruments_connection", "GPIB0::0", None, QtGui.QApplication.UnicodeUTF8))
        self.testcommand.setText(QtGui.QApplication.translate("Instruments_connection", "A,B,C", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Instruments_connection", "Write", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("Instruments_connection", "Ask", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("Instruments_connection", "Read", None, QtGui.QApplication.UnicodeUTF8))

