# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\leroux\Github\PyGMI\PyGMI_files\Macro_editor.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Macro_editor(object):
    def setupUi(self, Macro_editor):
        Macro_editor.setObjectName("Macro_editor")
        Macro_editor.resize(1044, 806)
        self.gridLayout = QtWidgets.QGridLayout(Macro_editor)
        self.gridLayout.setObjectName("gridLayout")
        self.macro_textbox = MyMacroEdit(Macro_editor)
        self.macro_textbox.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.macro_textbox.setBackgroundVisible(False)
        self.macro_textbox.setObjectName("macro_textbox")
        self.gridLayout.addWidget(self.macro_textbox, 0, 0, 1, 3)
        self.macrocommandtree = QtWidgets.QTreeView(Macro_editor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.macrocommandtree.sizePolicy().hasHeightForWidth())
        self.macrocommandtree.setSizePolicy(sizePolicy)
        self.macrocommandtree.setProperty("showDropIndicator", False)
        self.macrocommandtree.setAlternatingRowColors(True)
        self.macrocommandtree.setTextElideMode(QtCore.Qt.ElideRight)
        self.macrocommandtree.setRootIsDecorated(True)
        self.macrocommandtree.setUniformRowHeights(False)
        self.macrocommandtree.setItemsExpandable(True)
        self.macrocommandtree.setAnimated(False)
        self.macrocommandtree.setWordWrap(True)
        self.macrocommandtree.setExpandsOnDoubleClick(True)
        self.macrocommandtree.setObjectName("macrocommandtree")
        self.macrocommandtree.header().setHighlightSections(True)
        self.gridLayout.addWidget(self.macrocommandtree, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(Macro_editor)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.mac_curr_line = QtWidgets.QLineEdit(Macro_editor)
        self.mac_curr_line.setEnabled(False)
        self.mac_curr_line.setObjectName("mac_curr_line")
        self.gridLayout.addWidget(self.mac_curr_line, 2, 0, 1, 3)
        self.pushButton_8 = QtWidgets.QPushButton(Macro_editor)
        self.pushButton_8.setDefault(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 3, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(Macro_editor)
        self.pushButton_9.setDefault(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 3, 1, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(Macro_editor)
        self.pushButton_10.setDefault(False)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 3, 2, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(Macro_editor)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setDefault(False)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 4, 0, 1, 2)
        self.pushButton_12 = QtWidgets.QPushButton(Macro_editor)
        self.pushButton_12.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 26pt \"Arial\";")
        self.pushButton_12.setDefault(False)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 2, 3, 3, 1)

        self.retranslateUi(Macro_editor)
        self.pushButton_9.clicked.connect(Macro_editor.save_macro)
        self.pushButton_8.clicked.connect(Macro_editor.open_macro)
        self.pushButton_11.clicked.connect(Macro_editor.run_macro)
        self.pushButton_10.clicked.connect(self.macro_textbox.clear)
        self.pushButton_12.clicked.connect(Macro_editor.stop_macro)
        QtCore.QMetaObject.connectSlotsByName(Macro_editor)

    def retranslateUi(self, Macro_editor):
        _translate = QtCore.QCoreApplication.translate
        Macro_editor.setWindowTitle(_translate("Macro_editor", "Form"))
        self.label_2.setText(_translate("Macro_editor", "Current line in the macro"))
        self.pushButton_8.setText(_translate("Macro_editor", "Open Macro"))
        self.pushButton_9.setText(_translate("Macro_editor", "Save Macro"))
        self.pushButton_10.setText(_translate("Macro_editor", "Clear Macro"))
        self.pushButton_11.setText(_translate("Macro_editor", "Run Macro"))
        self.pushButton_12.setText(_translate("Macro_editor", "Stop Macro"))

from .Macro_editor_textbox import MyMacroEdit
