# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Plot2DDataWidget.ui'
#
# Created: Mon Oct 20 23:34:23 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Plot2DData(object):
    def setupUi(self, Plot2DData):
        Plot2DData.setObjectName("Plot2DData")
        Plot2DData.resize(707, 753)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Plot2DData.sizePolicy().hasHeightForWidth())
        Plot2DData.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(Plot2DData)
        self.gridLayout.setObjectName("gridLayout")
        self.plot_area = PlotWidget(Plot2DData)
        self.plot_area.setObjectName("plot_area")
        self.gridLayout.addWidget(self.plot_area, 0, 0, 1, 4)
        self.label_3 = QtGui.QLabel(Plot2DData)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.y_axis_box = QtGui.QComboBox(Plot2DData)
        self.y_axis_box.setObjectName("y_axis_box")
        self.gridLayout.addWidget(self.y_axis_box, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(Plot2DData)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 2, 1, 1)
        self.x_axis_box = QtGui.QComboBox(Plot2DData)
        self.x_axis_box.setObjectName("x_axis_box")
        self.gridLayout.addWidget(self.x_axis_box, 1, 3, 1, 1)
        self.pushButton = QtGui.QPushButton(Plot2DData)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(Plot2DData)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(Plot2DData)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 2, 1, 1)
        self.refresh_rate = QtGui.QDoubleSpinBox(Plot2DData)
        self.refresh_rate.setMinimumSize(QtCore.QSize(91, 0))
        self.refresh_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.refresh_rate.setPrefix("")
        self.refresh_rate.setDecimals(1)
        self.refresh_rate.setMinimum(0.1)
        self.refresh_rate.setMaximum(200000.0)
        self.refresh_rate.setSingleStep(0.5)
        self.refresh_rate.setProperty("value", 0.5)
        self.refresh_rate.setObjectName("refresh_rate")
        self.gridLayout.addWidget(self.refresh_rate, 2, 3, 1, 1)
        self.label = QtGui.QLabel(Plot2DData)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.Symbol_size = QtGui.QSpinBox(Plot2DData)
        self.Symbol_size.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Symbol_size.setSuffix("")
        self.Symbol_size.setPrefix("")
        self.Symbol_size.setProperty("value", 0)
        self.Symbol_size.setObjectName("Symbol_size")
        self.gridLayout.addWidget(self.Symbol_size, 3, 1, 1, 1)
        self.auto_upd = QtGui.QCheckBox(Plot2DData)
        self.auto_upd.setChecked(True)
        self.auto_upd.setObjectName("auto_upd")
        self.gridLayout.addWidget(self.auto_upd, 3, 3, 1, 1)
        self.autoconnect = QtGui.QCheckBox(Plot2DData)
        self.autoconnect.setChecked(True)
        self.autoconnect.setObjectName("autoconnect")
        self.gridLayout.addWidget(self.autoconnect, 3, 2, 1, 1)

        self.retranslateUi(Plot2DData)
        QtCore.QObject.connect(self.y_axis_box, QtCore.SIGNAL("currentIndexChanged(int)"), Plot2DData.updateY)
        QtCore.QObject.connect(self.x_axis_box, QtCore.SIGNAL("currentIndexChanged(int)"), Plot2DData.updateX)
        QtCore.QObject.connect(self.refresh_rate, QtCore.SIGNAL("valueChanged(double)"), Plot2DData.update_timer_timeout)
        QtCore.QObject.connect(self.Symbol_size, QtCore.SIGNAL("valueChanged(int)"), Plot2DData.change_symbol_size)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL("clicked()"), Plot2DData.change_point_color)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL("clicked()"), Plot2DData.change_line_color)
        QtCore.QObject.connect(self.auto_upd, QtCore.SIGNAL("stateChanged(int)"), Plot2DData.autoupdate)
        QtCore.QMetaObject.connectSlotsByName(Plot2DData)

    def retranslateUi(self, Plot2DData):
        Plot2DData.setWindowTitle(QtGui.QApplication.translate("Plot2DData", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Plot2DData", "Y-axis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Plot2DData", "X-axis", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Plot2DData", "Line Color", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("Plot2DData", "Point Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Plot2DData", "Refresh rate", None, QtGui.QApplication.UnicodeUTF8))
        self.refresh_rate.setSuffix(QtGui.QApplication.translate("Plot2DData", " s", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Plot2DData", "Point Size    ", None, QtGui.QApplication.UnicodeUTF8))
        self.auto_upd.setText(QtGui.QApplication.translate("Plot2DData", "Auto-update", None, QtGui.QApplication.UnicodeUTF8))
        self.autoconnect.setText(QtGui.QApplication.translate("Plot2DData", "Auto-connect", None, QtGui.QApplication.UnicodeUTF8))

from pyqtgraph import PlotWidget
