# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\leroux\Github\PyGMI\PyGMI_files\Plot2DDataWidget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Plot2DData(object):
    def setupUi(self, Plot2DData):
        Plot2DData.setObjectName("Plot2DData")
        Plot2DData.resize(707, 753)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Plot2DData.sizePolicy().hasHeightForWidth())
        Plot2DData.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Plot2DData)
        self.gridLayout.setObjectName("gridLayout")
        self.plot_area = PlotWidget(Plot2DData)
        self.plot_area.setObjectName("plot_area")
        self.gridLayout.addWidget(self.plot_area, 0, 0, 1, 4)
        self.label_3 = QtWidgets.QLabel(Plot2DData)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.y_axis_box = QtWidgets.QComboBox(Plot2DData)
        self.y_axis_box.setObjectName("y_axis_box")
        self.gridLayout.addWidget(self.y_axis_box, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(Plot2DData)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 2, 1, 1)
        self.x_axis_box = QtWidgets.QComboBox(Plot2DData)
        self.x_axis_box.setObjectName("x_axis_box")
        self.gridLayout.addWidget(self.x_axis_box, 1, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Plot2DData)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Plot2DData)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Plot2DData)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 2, 1, 1)
        self.refresh_rate = QtWidgets.QDoubleSpinBox(Plot2DData)
        self.refresh_rate.setMinimumSize(QtCore.QSize(91, 0))
        self.refresh_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.refresh_rate.setPrefix("")
        self.refresh_rate.setDecimals(1)
        self.refresh_rate.setMinimum(0.1)
        self.refresh_rate.setMaximum(200000.0)
        self.refresh_rate.setSingleStep(0.5)
        self.refresh_rate.setProperty("value", 0.5)
        self.refresh_rate.setObjectName("refresh_rate")
        self.gridLayout.addWidget(self.refresh_rate, 2, 3, 1, 1)
        self.label = QtWidgets.QLabel(Plot2DData)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.Symbol_size = QtWidgets.QSpinBox(Plot2DData)
        self.Symbol_size.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Symbol_size.setSuffix("")
        self.Symbol_size.setPrefix("")
        self.Symbol_size.setProperty("value", 0)
        self.Symbol_size.setObjectName("Symbol_size")
        self.gridLayout.addWidget(self.Symbol_size, 3, 1, 1, 1)
        self.auto_upd = QtWidgets.QCheckBox(Plot2DData)
        self.auto_upd.setChecked(True)
        self.auto_upd.setObjectName("auto_upd")
        self.gridLayout.addWidget(self.auto_upd, 3, 3, 1, 1)
        self.autoconnect = QtWidgets.QCheckBox(Plot2DData)
        self.autoconnect.setChecked(True)
        self.autoconnect.setObjectName("autoconnect")
        self.gridLayout.addWidget(self.autoconnect, 3, 2, 1, 1)

        self.retranslateUi(Plot2DData)
        self.y_axis_box.currentIndexChanged['int'].connect(Plot2DData.updateY)
        self.x_axis_box.currentIndexChanged['int'].connect(Plot2DData.updateX)
        self.refresh_rate.valueChanged['double'].connect(Plot2DData.update_timer_timeout)
        self.Symbol_size.valueChanged['int'].connect(Plot2DData.change_symbol_size)
        self.pushButton_2.clicked.connect(Plot2DData.change_point_color)
        self.pushButton.clicked.connect(Plot2DData.change_line_color)
        self.auto_upd.stateChanged['int'].connect(Plot2DData.autoupdate)
        QtCore.QMetaObject.connectSlotsByName(Plot2DData)

    def retranslateUi(self, Plot2DData):
        _translate = QtCore.QCoreApplication.translate
        Plot2DData.setWindowTitle(_translate("Plot2DData", "Form"))
        self.label_3.setText(_translate("Plot2DData", "Y-axis"))
        self.label_9.setText(_translate("Plot2DData", "X-axis"))
        self.pushButton.setText(_translate("Plot2DData", "Line Color"))
        self.pushButton_2.setText(_translate("Plot2DData", "Point Color"))
        self.label_6.setText(_translate("Plot2DData", "Refresh rate"))
        self.refresh_rate.setSuffix(_translate("Plot2DData", " s"))
        self.label.setText(_translate("Plot2DData", "Point Size    "))
        self.auto_upd.setText(_translate("Plot2DData", "Auto-update"))
        self.autoconnect.setText(_translate("Plot2DData", "Auto-connect"))

from pyqtgraph import PlotWidget
