# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyGMI_files\Instruments_panels\AAA_Test_instruments.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Panel(object):
    def setupUi(self, Panel):
        Panel.setObjectName(_fromUtf8("Panel"))
        Panel.resize(413, 183)
        self.gridLayout = QtGui.QGridLayout(Panel)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_7 = QtGui.QPushButton(Panel)
        self.pushButton_7.setDefault(False)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout.addWidget(self.pushButton_7, 1, 2, 1, 1)
        self.temp_controller_setpoint = QtGui.QDoubleSpinBox(Panel)
        self.temp_controller_setpoint.setMinimumSize(QtCore.QSize(91, 0))
        self.temp_controller_setpoint.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_controller_setpoint.setDecimals(3)
        self.temp_controller_setpoint.setMaximum(330.0)
        self.temp_controller_setpoint.setSingleStep(0.1)
        self.temp_controller_setpoint.setProperty("value", 2.0)
        self.temp_controller_setpoint.setObjectName(_fromUtf8("temp_controller_setpoint"))
        self.gridLayout.addWidget(self.temp_controller_setpoint, 4, 2, 1, 1)
        self.label_75 = QtGui.QLabel(Panel)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.gridLayout.addWidget(self.label_75, 5, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_72 = QtGui.QLabel(Panel)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.gridLayout.addWidget(self.label_72, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton_6 = QtGui.QPushButton(Panel)
        self.pushButton_6.setDefault(False)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout.addWidget(self.pushButton_6, 4, 3, 1, 1)
        self.temp_controller_P = QtGui.QDoubleSpinBox(Panel)
        self.temp_controller_P.setMinimumSize(QtCore.QSize(91, 0))
        self.temp_controller_P.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_controller_P.setSuffix(_fromUtf8(""))
        self.temp_controller_P.setDecimals(3)
        self.temp_controller_P.setMaximum(9999999.0)
        self.temp_controller_P.setSingleStep(0.1)
        self.temp_controller_P.setProperty("value", 0.0)
        self.temp_controller_P.setObjectName(_fromUtf8("temp_controller_P"))
        self.gridLayout.addWidget(self.temp_controller_P, 6, 0, 1, 1)
        self.temp_controller_I = QtGui.QDoubleSpinBox(Panel)
        self.temp_controller_I.setMinimumSize(QtCore.QSize(91, 0))
        self.temp_controller_I.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_controller_I.setSuffix(_fromUtf8(""))
        self.temp_controller_I.setDecimals(3)
        self.temp_controller_I.setMaximum(9999999.0)
        self.temp_controller_I.setSingleStep(10.0)
        self.temp_controller_I.setProperty("value", 0.0)
        self.temp_controller_I.setObjectName(_fromUtf8("temp_controller_I"))
        self.gridLayout.addWidget(self.temp_controller_I, 6, 1, 1, 1)
        self.temp_controller_loop = QtGui.QSpinBox(Panel)
        self.temp_controller_loop.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_controller_loop.setMinimum(1)
        self.temp_controller_loop.setObjectName(_fromUtf8("temp_controller_loop"))
        self.gridLayout.addWidget(self.temp_controller_loop, 4, 1, 1, 1)
        self.temp_controller_D = QtGui.QDoubleSpinBox(Panel)
        self.temp_controller_D.setMinimumSize(QtCore.QSize(91, 0))
        self.temp_controller_D.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_controller_D.setSuffix(_fromUtf8(""))
        self.temp_controller_D.setDecimals(3)
        self.temp_controller_D.setMaximum(9999999.0)
        self.temp_controller_D.setSingleStep(1.0)
        self.temp_controller_D.setProperty("value", 0.0)
        self.temp_controller_D.setObjectName(_fromUtf8("temp_controller_D"))
        self.gridLayout.addWidget(self.temp_controller_D, 6, 2, 1, 1)
        self.temp_controller_channel = QtGui.QComboBox(Panel)
        self.temp_controller_channel.setObjectName(_fromUtf8("temp_controller_channel"))
        self.temp_controller_channel.addItem(_fromUtf8(""))
        self.temp_controller_channel.addItem(_fromUtf8(""))
        self.temp_controller_channel.addItem(_fromUtf8(""))
        self.temp_controller_channel.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.temp_controller_channel, 4, 0, 1, 1)
        self.temp_controller_ramprate = QtGui.QDoubleSpinBox(Panel)
        self.temp_controller_ramprate.setMinimumSize(QtCore.QSize(91, 0))
        self.temp_controller_ramprate.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_controller_ramprate.setDecimals(2)
        self.temp_controller_ramprate.setMaximum(200000.0)
        self.temp_controller_ramprate.setSingleStep(1.0)
        self.temp_controller_ramprate.setProperty("value", 10.0)
        self.temp_controller_ramprate.setObjectName(_fromUtf8("temp_controller_ramprate"))
        self.gridLayout.addWidget(self.temp_controller_ramprate, 1, 0, 1, 1)
        self.label_45 = QtGui.QLabel(Panel)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout.addWidget(self.label_45, 0, 0, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(Panel)
        self.pushButton_5.setDefault(False)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.label_76 = QtGui.QLabel(Panel)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.gridLayout.addWidget(self.label_76, 5, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_46 = QtGui.QLabel(Panel)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout.addWidget(self.label_46, 3, 1, 1, 1)
        self.label_24 = QtGui.QLabel(Panel)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout.addWidget(self.label_24, 3, 0, 1, 1)
        self.label_44 = QtGui.QLabel(Panel)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout.addWidget(self.label_44, 3, 2, 1, 1)

        self.retranslateUi(Panel)
        QtCore.QMetaObject.connectSlotsByName(Panel)

    def retranslateUi(self, Panel):
        Panel.setWindowTitle(_translate("Panel", "Lakeshore - 340", None))
        self.pushButton_7.setText(_translate("Panel", "OFF", None))
        self.temp_controller_setpoint.setSuffix(_translate("Panel", " K", None))
        self.label_75.setText(_translate("Panel", "I", None))
        self.label_72.setText(_translate("Panel", "P", None))
        self.pushButton_6.setText(_translate("Panel", "Set", None))
        self.temp_controller_loop.setPrefix(_translate("Panel", "loop ", None))
        self.temp_controller_channel.setItemText(0, _translate("Panel", "A", None))
        self.temp_controller_channel.setItemText(1, _translate("Panel", "B", None))
        self.temp_controller_channel.setItemText(2, _translate("Panel", "C", None))
        self.temp_controller_channel.setItemText(3, _translate("Panel", "D", None))
        self.temp_controller_ramprate.setSuffix(_translate("Panel", " K/min", None))
        self.label_45.setText(_translate("Panel", "Ramp Rate", None))
        self.pushButton_5.setText(_translate("Panel", "ON", None))
        self.label_76.setText(_translate("Panel", "D", None))
        self.label_46.setText(_translate("Panel", "Control loop", None))
        self.label_24.setText(_translate("Panel", "Channel", None))
        self.label_44.setText(_translate("Panel", "Setpoint", None))

