# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\leroux\Github\PyGMI\PyGMI_files\Instruments_panels\Keithley6221.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Panel(object):
    def setupUi(self, Panel):
        Panel.setObjectName("Panel")
        Panel.resize(479, 70)
        self.gridLayout = QtWidgets.QGridLayout(Panel)
        self.gridLayout.setObjectName("gridLayout")
        self.I_disp = QtWidgets.QLabel(Panel)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.I_disp.setFont(font)
        self.I_disp.setAutoFillBackground(False)
        self.I_disp.setStyleSheet("background-color: rgb(0, 1, 0);\n"
"color: rgb(250, 28, 51);")
        self.I_disp.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.I_disp.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.I_disp.setScaledContents(False)
        self.I_disp.setAlignment(QtCore.Qt.AlignCenter)
        self.I_disp.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.I_disp.setObjectName("I_disp")
        self.gridLayout.addWidget(self.I_disp, 0, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Panel)
        self.doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setMinimum(-1000000.0)
        self.doubleSpinBox.setMaximum(1000000.0)
        self.doubleSpinBox.setSingleStep(50.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 0, 1, 1, 1)
        self.outputON = QtWidgets.QRadioButton(Panel)
        self.outputON.setObjectName("outputON")
        self.gridLayout.addWidget(self.outputON, 0, 2, 1, 1)
        self.label_47 = QtWidgets.QLabel(Panel)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.gridLayout.addWidget(self.label_47, 0, 3, 1, 1)
        self.monitor = QtWidgets.QCheckBox(Panel)
        self.monitor.setChecked(False)
        self.monitor.setObjectName("monitor")
        self.gridLayout.addWidget(self.monitor, 0, 4, 1, 1)
        self.V_disp = QtWidgets.QLabel(Panel)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.V_disp.setFont(font)
        self.V_disp.setAutoFillBackground(False)
        self.V_disp.setStyleSheet("background-color: rgb(0, 1, 0);\n"
"color: rgb(250, 28, 51);")
        self.V_disp.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.V_disp.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.V_disp.setScaledContents(False)
        self.V_disp.setAlignment(QtCore.Qt.AlignCenter)
        self.V_disp.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.V_disp.setObjectName("V_disp")
        self.gridLayout.addWidget(self.V_disp, 1, 0, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(Panel)
        self.doubleSpinBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_2.setDecimals(3)
        self.doubleSpinBox_2.setMinimum(-50.0)
        self.doubleSpinBox_2.setMaximum(50.0)
        self.doubleSpinBox_2.setSingleStep(1.0)
        self.doubleSpinBox_2.setProperty("value", 10.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout.addWidget(self.doubleSpinBox_2, 1, 1, 1, 1)
        self.resetbutton = QtWidgets.QPushButton(Panel)
        self.resetbutton.setObjectName("resetbutton")
        self.gridLayout.addWidget(self.resetbutton, 1, 2, 1, 1)
        self.refresh_rate = QtWidgets.QDoubleSpinBox(Panel)
        self.refresh_rate.setMinimumSize(QtCore.QSize(91, 0))
        self.refresh_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.refresh_rate.setDecimals(1)
        self.refresh_rate.setMaximum(9999999.0)
        self.refresh_rate.setSingleStep(0.5)
        self.refresh_rate.setProperty("value", 2.0)
        self.refresh_rate.setObjectName("refresh_rate")
        self.gridLayout.addWidget(self.refresh_rate, 1, 3, 1, 2)

        self.retranslateUi(Panel)
        self.monitor.clicked['bool'].connect(Panel.monitor)
        self.refresh_rate.valueChanged['double'].connect(Panel.update_timer_timeout)
        self.doubleSpinBox.valueChanged['double'].connect(Panel.change_I)
        self.doubleSpinBox_2.valueChanged['double'].connect(Panel.change_V_comp)
        self.outputON.clicked['bool'].connect(Panel.switch_output)
        self.resetbutton.clicked.connect(Panel.reset_inst)
        QtCore.QMetaObject.connectSlotsByName(Panel)

    def retranslateUi(self, Panel):
        _translate = QtCore.QCoreApplication.translate
        Panel.setWindowTitle(_translate("Panel", "Keithley 6221"))
        self.I_disp.setText(_translate("Panel", "--- μA"))
        self.doubleSpinBox.setSuffix(_translate("Panel", " μA"))
        self.outputON.setText(_translate("Panel", "Output ON"))
        self.label_47.setText(_translate("Panel", "Refresh rate"))
        self.monitor.setText(_translate("Panel", "Monitor"))
        self.V_disp.setText(_translate("Panel", "--- V"))
        self.doubleSpinBox_2.setSuffix(_translate("Panel", " V"))
        self.resetbutton.setText(_translate("Panel", "Reset"))
        self.refresh_rate.setSuffix(_translate("Panel", " secs"))

