# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\leroux\Github\PyGMI\PyGMI_files\Instruments_panels\Lakeshore340.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Panel(object):
    def setupUi(self, Panel):
        Panel.setObjectName("Panel")
        Panel.resize(411, 189)
        self.gridLayout = QtWidgets.QGridLayout(Panel)
        self.gridLayout.setObjectName("gridLayout")
        self.label_72 = QtWidgets.QLabel(Panel)
        self.label_72.setObjectName("label_72")
        self.gridLayout.addWidget(self.label_72, 6, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton_7 = QtWidgets.QPushButton(Panel)
        self.pushButton_7.setDefault(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 2, 3, 1, 1)
        self.checkTbox = QtWidgets.QCheckBox(Panel)
        self.checkTbox.setChecked(False)
        self.checkTbox.setObjectName("checkTbox")
        self.gridLayout.addWidget(self.checkTbox, 1, 1, 1, 1)
        self.T_display = QtWidgets.QLabel(Panel)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.T_display.setFont(font)
        self.T_display.setAutoFillBackground(False)
        self.T_display.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.T_display.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.T_display.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.T_display.setScaledContents(False)
        self.T_display.setAlignment(QtCore.Qt.AlignCenter)
        self.T_display.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.T_display.setObjectName("T_display")
        self.gridLayout.addWidget(self.T_display, 1, 0, 1, 1)
        self.temp_controller_I = QtWidgets.QDoubleSpinBox(Panel)
        self.temp_controller_I.setMinimumSize(QtCore.QSize(91, 0))
        self.temp_controller_I.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_controller_I.setSuffix("")
        self.temp_controller_I.setDecimals(3)
        self.temp_controller_I.setMaximum(9999999.0)
        self.temp_controller_I.setSingleStep(10.0)
        self.temp_controller_I.setProperty("value", 0.0)
        self.temp_controller_I.setObjectName("temp_controller_I")
        self.gridLayout.addWidget(self.temp_controller_I, 7, 1, 1, 1)
        self.label_75 = QtWidgets.QLabel(Panel)
        self.label_75.setObjectName("label_75")
        self.gridLayout.addWidget(self.label_75, 6, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_45 = QtWidgets.QLabel(Panel)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout.addWidget(self.label_45, 2, 0, 1, 1)
        self.temp_controller_loop = QtWidgets.QSpinBox(Panel)
        self.temp_controller_loop.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_controller_loop.setMinimum(1)
        self.temp_controller_loop.setObjectName("temp_controller_loop")
        self.gridLayout.addWidget(self.temp_controller_loop, 5, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(Panel)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 4, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(Panel)
        self.pushButton_5.setDefault(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 2, 2, 1, 1)
        self.temp_controller_ramprate = QtWidgets.QDoubleSpinBox(Panel)
        self.temp_controller_ramprate.setMinimumSize(QtCore.QSize(91, 0))
        self.temp_controller_ramprate.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_controller_ramprate.setDecimals(2)
        self.temp_controller_ramprate.setMaximum(200000.0)
        self.temp_controller_ramprate.setSingleStep(1.0)
        self.temp_controller_ramprate.setProperty("value", 10.0)
        self.temp_controller_ramprate.setObjectName("temp_controller_ramprate")
        self.gridLayout.addWidget(self.temp_controller_ramprate, 2, 1, 1, 1)
        self.temp_controller_setpoint = QtWidgets.QDoubleSpinBox(Panel)
        self.temp_controller_setpoint.setMinimumSize(QtCore.QSize(91, 0))
        self.temp_controller_setpoint.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_controller_setpoint.setDecimals(3)
        self.temp_controller_setpoint.setMaximum(330.0)
        self.temp_controller_setpoint.setSingleStep(0.1)
        self.temp_controller_setpoint.setProperty("value", 2.0)
        self.temp_controller_setpoint.setObjectName("temp_controller_setpoint")
        self.gridLayout.addWidget(self.temp_controller_setpoint, 5, 2, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(Panel)
        self.pushButton_6.setDefault(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 5, 3, 1, 1)
        self.temp_controller_P = QtWidgets.QDoubleSpinBox(Panel)
        self.temp_controller_P.setMinimumSize(QtCore.QSize(91, 0))
        self.temp_controller_P.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_controller_P.setSuffix("")
        self.temp_controller_P.setDecimals(3)
        self.temp_controller_P.setMaximum(9999999.0)
        self.temp_controller_P.setSingleStep(0.1)
        self.temp_controller_P.setProperty("value", 0.0)
        self.temp_controller_P.setObjectName("temp_controller_P")
        self.gridLayout.addWidget(self.temp_controller_P, 7, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(Panel)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.gridLayout.addWidget(self.label_44, 4, 2, 1, 1)
        self.temp_controller_D = QtWidgets.QDoubleSpinBox(Panel)
        self.temp_controller_D.setMinimumSize(QtCore.QSize(91, 0))
        self.temp_controller_D.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_controller_D.setSuffix("")
        self.temp_controller_D.setDecimals(3)
        self.temp_controller_D.setMaximum(9999999.0)
        self.temp_controller_D.setSingleStep(1.0)
        self.temp_controller_D.setProperty("value", 0.0)
        self.temp_controller_D.setObjectName("temp_controller_D")
        self.gridLayout.addWidget(self.temp_controller_D, 7, 2, 1, 1)
        self.label_76 = QtWidgets.QLabel(Panel)
        self.label_76.setObjectName("label_76")
        self.gridLayout.addWidget(self.label_76, 6, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.temp_controller_channel = QtWidgets.QComboBox(Panel)
        self.temp_controller_channel.setObjectName("temp_controller_channel")
        self.temp_controller_channel.addItem("")
        self.temp_controller_channel.addItem("")
        self.temp_controller_channel.addItem("")
        self.temp_controller_channel.addItem("")
        self.gridLayout.addWidget(self.temp_controller_channel, 5, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(Panel)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.gridLayout.addWidget(self.label_46, 4, 1, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(Panel)
        self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox.setMaximum(5)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 7, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(Panel)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 3, 1, 1)
        self.refresh_rate = QtWidgets.QDoubleSpinBox(Panel)
        self.refresh_rate.setMinimumSize(QtCore.QSize(91, 0))
        self.refresh_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.refresh_rate.setDecimals(1)
        self.refresh_rate.setMaximum(9999999.0)
        self.refresh_rate.setSingleStep(0.5)
        self.refresh_rate.setProperty("value", 2.0)
        self.refresh_rate.setObjectName("refresh_rate")
        self.gridLayout.addWidget(self.refresh_rate, 1, 3, 1, 1)
        self.label_47 = QtWidgets.QLabel(Panel)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.gridLayout.addWidget(self.label_47, 1, 2, 1, 1)

        self.retranslateUi(Panel)
        self.pushButton_6.clicked.connect(Panel.set_setpoint)
        self.pushButton_7.clicked.connect(Panel.stop_ramp)
        self.pushButton_5.clicked.connect(Panel.init_ramp)
        self.temp_controller_P.valueChanged['double'].connect(Panel.PID_P_update)
        self.temp_controller_I.valueChanged['double'].connect(Panel.PID_I_update)
        self.temp_controller_D.valueChanged['double'].connect(Panel.PID_D_update)
        self.spinBox.valueChanged['int'].connect(Panel.set_heater_range)
        self.refresh_rate.valueChanged['double'].connect(Panel.update_timer_timeout)
        self.checkTbox.clicked['bool'].connect(Panel.autocheckT)
        QtCore.QMetaObject.connectSlotsByName(Panel)

    def retranslateUi(self, Panel):
        _translate = QtCore.QCoreApplication.translate
        Panel.setWindowTitle(_translate("Panel", "Lakeshore - 340"))
        self.label_72.setText(_translate("Panel", "P"))
        self.pushButton_7.setText(_translate("Panel", "OFF"))
        self.checkTbox.setText(_translate("Panel", "Monitor T"))
        self.T_display.setText(_translate("Panel", "--- K"))
        self.label_75.setText(_translate("Panel", "I"))
        self.label_45.setText(_translate("Panel", "Ramp Rate :"))
        self.temp_controller_loop.setPrefix(_translate("Panel", "loop "))
        self.label_24.setText(_translate("Panel", "Channel"))
        self.pushButton_5.setText(_translate("Panel", "ON"))
        self.temp_controller_ramprate.setSuffix(_translate("Panel", " K/min"))
        self.temp_controller_setpoint.setSuffix(_translate("Panel", " K"))
        self.pushButton_6.setText(_translate("Panel", "Set"))
        self.label_44.setText(_translate("Panel", "Setpoint"))
        self.label_76.setText(_translate("Panel", "D"))
        self.temp_controller_channel.setItemText(0, _translate("Panel", "A"))
        self.temp_controller_channel.setItemText(1, _translate("Panel", "B"))
        self.temp_controller_channel.setItemText(2, _translate("Panel", "C"))
        self.temp_controller_channel.setItemText(3, _translate("Panel", "D"))
        self.label_46.setText(_translate("Panel", "Control loop"))
        self.label_2.setText(_translate("Panel", "Heater range"))
        self.refresh_rate.setSuffix(_translate("Panel", " secs"))
        self.label_47.setText(_translate("Panel", "Refresh rate :"))

