# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyGMI_files\Instruments_panels\Lakeshore340.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Panel(object):
    def setupUi(self, Panel):
        Panel.setObjectName(_fromUtf8("Panel"))
        Panel.resize(411, 189)
        self.gridLayout = QtGui.QGridLayout(Panel)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_72 = QtGui.QLabel(Panel)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.gridLayout.addWidget(self.label_72, 6, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton_7 = QtGui.QPushButton(Panel)
        self.pushButton_7.setDefault(False)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout.addWidget(self.pushButton_7, 2, 3, 1, 1)
        self.checkTbox = QtGui.QCheckBox(Panel)
        self.checkTbox.setChecked(False)
        self.checkTbox.setObjectName(_fromUtf8("checkTbox"))
        self.gridLayout.addWidget(self.checkTbox, 1, 1, 1, 1)
        self.T_display = QtGui.QLabel(Panel)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.T_display.setFont(font)
        self.T_display.setAutoFillBackground(False)
        self.T_display.setStyleSheet(_fromUtf8("background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);"))
        self.T_display.setFrameShape(QtGui.QFrame.WinPanel)
        self.T_display.setFrameShadow(QtGui.QFrame.Sunken)
        self.T_display.setScaledContents(False)
        self.T_display.setAlignment(QtCore.Qt.AlignCenter)
        self.T_display.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.T_display.setObjectName(_fromUtf8("T_display"))
        self.gridLayout.addWidget(self.T_display, 1, 0, 1, 1)
        self.temp_controller_I = QtGui.QDoubleSpinBox(Panel)
        self.temp_controller_I.setMinimumSize(QtCore.QSize(91, 0))
        self.temp_controller_I.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_controller_I.setSuffix(_fromUtf8(""))
        self.temp_controller_I.setDecimals(3)
        self.temp_controller_I.setMaximum(9999999.0)
        self.temp_controller_I.setSingleStep(10.0)
        self.temp_controller_I.setProperty("value", 0.0)
        self.temp_controller_I.setObjectName(_fromUtf8("temp_controller_I"))
        self.gridLayout.addWidget(self.temp_controller_I, 7, 1, 1, 1)
        self.label_75 = QtGui.QLabel(Panel)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.gridLayout.addWidget(self.label_75, 6, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_45 = QtGui.QLabel(Panel)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout.addWidget(self.label_45, 2, 0, 1, 1)
        self.temp_controller_loop = QtGui.QSpinBox(Panel)
        self.temp_controller_loop.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_controller_loop.setMinimum(1)
        self.temp_controller_loop.setObjectName(_fromUtf8("temp_controller_loop"))
        self.gridLayout.addWidget(self.temp_controller_loop, 5, 1, 1, 1)
        self.label_24 = QtGui.QLabel(Panel)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout.addWidget(self.label_24, 4, 0, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(Panel)
        self.pushButton_5.setDefault(False)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout.addWidget(self.pushButton_5, 2, 2, 1, 1)
        self.temp_controller_ramprate = QtGui.QDoubleSpinBox(Panel)
        self.temp_controller_ramprate.setMinimumSize(QtCore.QSize(91, 0))
        self.temp_controller_ramprate.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_controller_ramprate.setDecimals(2)
        self.temp_controller_ramprate.setMaximum(200000.0)
        self.temp_controller_ramprate.setSingleStep(1.0)
        self.temp_controller_ramprate.setProperty("value", 10.0)
        self.temp_controller_ramprate.setObjectName(_fromUtf8("temp_controller_ramprate"))
        self.gridLayout.addWidget(self.temp_controller_ramprate, 2, 1, 1, 1)
        self.temp_controller_setpoint = QtGui.QDoubleSpinBox(Panel)
        self.temp_controller_setpoint.setMinimumSize(QtCore.QSize(91, 0))
        self.temp_controller_setpoint.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_controller_setpoint.setDecimals(3)
        self.temp_controller_setpoint.setMaximum(330.0)
        self.temp_controller_setpoint.setSingleStep(0.1)
        self.temp_controller_setpoint.setProperty("value", 2.0)
        self.temp_controller_setpoint.setObjectName(_fromUtf8("temp_controller_setpoint"))
        self.gridLayout.addWidget(self.temp_controller_setpoint, 5, 2, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(Panel)
        self.pushButton_6.setDefault(False)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout.addWidget(self.pushButton_6, 5, 3, 1, 1)
        self.temp_controller_P = QtGui.QDoubleSpinBox(Panel)
        self.temp_controller_P.setMinimumSize(QtCore.QSize(91, 0))
        self.temp_controller_P.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_controller_P.setSuffix(_fromUtf8(""))
        self.temp_controller_P.setDecimals(3)
        self.temp_controller_P.setMaximum(9999999.0)
        self.temp_controller_P.setSingleStep(0.1)
        self.temp_controller_P.setProperty("value", 0.0)
        self.temp_controller_P.setObjectName(_fromUtf8("temp_controller_P"))
        self.gridLayout.addWidget(self.temp_controller_P, 7, 0, 1, 1)
        self.label_44 = QtGui.QLabel(Panel)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout.addWidget(self.label_44, 4, 2, 1, 1)
        self.temp_controller_D = QtGui.QDoubleSpinBox(Panel)
        self.temp_controller_D.setMinimumSize(QtCore.QSize(91, 0))
        self.temp_controller_D.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_controller_D.setSuffix(_fromUtf8(""))
        self.temp_controller_D.setDecimals(3)
        self.temp_controller_D.setMaximum(9999999.0)
        self.temp_controller_D.setSingleStep(1.0)
        self.temp_controller_D.setProperty("value", 0.0)
        self.temp_controller_D.setObjectName(_fromUtf8("temp_controller_D"))
        self.gridLayout.addWidget(self.temp_controller_D, 7, 2, 1, 1)
        self.label_76 = QtGui.QLabel(Panel)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.gridLayout.addWidget(self.label_76, 6, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.temp_controller_channel = QtGui.QComboBox(Panel)
        self.temp_controller_channel.setObjectName(_fromUtf8("temp_controller_channel"))
        self.temp_controller_channel.addItem(_fromUtf8(""))
        self.temp_controller_channel.addItem(_fromUtf8(""))
        self.temp_controller_channel.addItem(_fromUtf8(""))
        self.temp_controller_channel.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.temp_controller_channel, 5, 0, 1, 1)
        self.label_46 = QtGui.QLabel(Panel)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout.addWidget(self.label_46, 4, 1, 1, 1)
        self.spinBox = QtGui.QSpinBox(Panel)
        self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox.setMaximum(5)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout.addWidget(self.spinBox, 7, 3, 1, 1)
        self.label_2 = QtGui.QLabel(Panel)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 6, 3, 1, 1)
        self.refresh_rate = QtGui.QDoubleSpinBox(Panel)
        self.refresh_rate.setMinimumSize(QtCore.QSize(91, 0))
        self.refresh_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.refresh_rate.setDecimals(1)
        self.refresh_rate.setMaximum(9999999.0)
        self.refresh_rate.setSingleStep(0.5)
        self.refresh_rate.setProperty("value", 2.0)
        self.refresh_rate.setObjectName(_fromUtf8("refresh_rate"))
        self.gridLayout.addWidget(self.refresh_rate, 1, 3, 1, 1)
        self.label_47 = QtGui.QLabel(Panel)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout.addWidget(self.label_47, 1, 2, 1, 1)

        self.retranslateUi(Panel)
        QtCore.QObject.connect(self.pushButton_6, QtCore.SIGNAL(_fromUtf8("clicked()")), Panel.set_setpoint)
        QtCore.QObject.connect(self.pushButton_7, QtCore.SIGNAL(_fromUtf8("clicked()")), Panel.stop_ramp)
        QtCore.QObject.connect(self.pushButton_5, QtCore.SIGNAL(_fromUtf8("clicked()")), Panel.init_ramp)
        QtCore.QObject.connect(self.temp_controller_P, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), Panel.PID_P_update)
        QtCore.QObject.connect(self.temp_controller_I, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), Panel.PID_I_update)
        QtCore.QObject.connect(self.temp_controller_D, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), Panel.PID_D_update)
        QtCore.QObject.connect(self.spinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), Panel.set_heater_range)
        QtCore.QObject.connect(self.refresh_rate, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), Panel.update_timer_timeout)
        QtCore.QObject.connect(self.checkTbox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), Panel.autocheckT)
        QtCore.QMetaObject.connectSlotsByName(Panel)

    def retranslateUi(self, Panel):
        Panel.setWindowTitle(_translate("Panel", "Lakeshore - 340", None))
        self.label_72.setText(_translate("Panel", "P", None))
        self.pushButton_7.setText(_translate("Panel", "OFF", None))
        self.checkTbox.setText(_translate("Panel", "Monitor T", None))
        self.T_display.setText(_translate("Panel", "--- K", None))
        self.label_75.setText(_translate("Panel", "I", None))
        self.label_45.setText(_translate("Panel", "Ramp Rate :", None))
        self.temp_controller_loop.setPrefix(_translate("Panel", "loop ", None))
        self.label_24.setText(_translate("Panel", "Channel", None))
        self.pushButton_5.setText(_translate("Panel", "ON", None))
        self.temp_controller_ramprate.setSuffix(_translate("Panel", " K/min", None))
        self.temp_controller_setpoint.setSuffix(_translate("Panel", " K", None))
        self.pushButton_6.setText(_translate("Panel", "Set", None))
        self.label_44.setText(_translate("Panel", "Setpoint", None))
        self.label_76.setText(_translate("Panel", "D", None))
        self.temp_controller_channel.setItemText(0, _translate("Panel", "A", None))
        self.temp_controller_channel.setItemText(1, _translate("Panel", "B", None))
        self.temp_controller_channel.setItemText(2, _translate("Panel", "C", None))
        self.temp_controller_channel.setItemText(3, _translate("Panel", "D", None))
        self.label_46.setText(_translate("Panel", "Control loop", None))
        self.label_2.setText(_translate("Panel", "Heater range", None))
        self.refresh_rate.setSuffix(_translate("Panel", " secs", None))
        self.label_47.setText(_translate("Panel", "Refresh rate :", None))

