# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\leroux\Github\PyGMI\PyGMI_files\Instruments_panels\SR830.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Panel(object):
    def setupUi(self, Panel):
        Panel.setObjectName("Panel")
        Panel.resize(486, 162)
        self.gridLayout = QtWidgets.QGridLayout(Panel)
        self.gridLayout.setObjectName("gridLayout")
        self.channel = QtWidgets.QComboBox(Panel)
        self.channel.setObjectName("channel")
        self.channel.addItem("")
        self.channel.addItem("")
        self.channel.addItem("")
        self.channel.addItem("")
        self.channel.addItem("")
        self.gridLayout.addWidget(self.channel, 1, 1, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Panel)
        self.doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox.setDecimals(4)
        self.doubleSpinBox.setMaximum(200000.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(Panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(Panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.x_disp = QtWidgets.QLabel(Panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_disp.sizePolicy().hasHeightForWidth())
        self.x_disp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.x_disp.setFont(font)
        self.x_disp.setAutoFillBackground(False)
        self.x_disp.setStyleSheet("background-color: rgb(0, 1, 0);\n"
"color: rgb(250, 28, 51);")
        self.x_disp.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.x_disp.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.x_disp.setScaledContents(False)
        self.x_disp.setAlignment(QtCore.Qt.AlignCenter)
        self.x_disp.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.x_disp.setObjectName("x_disp")
        self.gridLayout.addWidget(self.x_disp, 0, 1, 1, 1)
        self.y_disp = QtWidgets.QLabel(Panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_disp.sizePolicy().hasHeightForWidth())
        self.y_disp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.y_disp.setFont(font)
        self.y_disp.setAutoFillBackground(False)
        self.y_disp.setStyleSheet("background-color: rgb(0, 1, 0);\n"
"color: rgb(250, 28, 51);")
        self.y_disp.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.y_disp.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.y_disp.setScaledContents(False)
        self.y_disp.setAlignment(QtCore.Qt.AlignCenter)
        self.y_disp.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.y_disp.setObjectName("y_disp")
        self.gridLayout.addWidget(self.y_disp, 0, 2, 1, 1)
        self.f_disp = QtWidgets.QLabel(Panel)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.f_disp.setFont(font)
        self.f_disp.setAutoFillBackground(False)
        self.f_disp.setStyleSheet("background-color: rgb(0, 1, 0);\n"
"color: rgb(250, 28, 51);")
        self.f_disp.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.f_disp.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.f_disp.setScaledContents(False)
        self.f_disp.setAlignment(QtCore.Qt.AlignCenter)
        self.f_disp.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.f_disp.setObjectName("f_disp")
        self.gridLayout.addWidget(self.f_disp, 0, 3, 1, 1)
        self.sense = QtWidgets.QComboBox(Panel)
        self.sense.setObjectName("sense")
        self.sense.addItem("")
        self.sense.addItem("")
        self.sense.addItem("")
        self.sense.addItem("")
        self.sense.addItem("")
        self.sense.addItem("")
        self.sense.addItem("")
        self.sense.addItem("")
        self.sense.addItem("")
        self.sense.addItem("")
        self.sense.addItem("")
        self.sense.addItem("")
        self.sense.addItem("")
        self.sense.addItem("")
        self.sense.addItem("")
        self.sense.addItem("")
        self.sense.addItem("")
        self.sense.addItem("")
        self.sense.addItem("")
        self.sense.addItem("")
        self.sense.addItem("")
        self.sense.addItem("")
        self.sense.addItem("")
        self.sense.addItem("")
        self.sense.addItem("")
        self.sense.addItem("")
        self.sense.addItem("")
        self.gridLayout.addWidget(self.sense, 1, 0, 1, 1)
        self.a_disp = QtWidgets.QLabel(Panel)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.a_disp.setFont(font)
        self.a_disp.setAutoFillBackground(False)
        self.a_disp.setStyleSheet("background-color: rgb(0, 1, 0);\n"
"color: rgb(250, 28, 51);")
        self.a_disp.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.a_disp.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.a_disp.setScaledContents(False)
        self.a_disp.setAlignment(QtCore.Qt.AlignCenter)
        self.a_disp.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.a_disp.setObjectName("a_disp")
        self.gridLayout.addWidget(self.a_disp, 3, 3, 1, 1)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(Panel)
        self.doubleSpinBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_3.setDecimals(3)
        self.doubleSpinBox_3.setMinimum(-20000.0)
        self.doubleSpinBox_3.setMaximum(20000.0)
        self.doubleSpinBox_3.setSingleStep(0.01)
        self.doubleSpinBox_3.setProperty("value", 0.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout.addWidget(self.doubleSpinBox_3, 6, 3, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(Panel)
        self.doubleSpinBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_2.setDecimals(3)
        self.doubleSpinBox_2.setMinimum(0.0)
        self.doubleSpinBox_2.setMaximum(200000.0)
        self.doubleSpinBox_2.setSingleStep(0.01)
        self.doubleSpinBox_2.setProperty("value", 0.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout.addWidget(self.doubleSpinBox_2, 4, 3, 1, 1)
        self.ph_disp = QtWidgets.QLabel(Panel)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.ph_disp.setFont(font)
        self.ph_disp.setAutoFillBackground(False)
        self.ph_disp.setStyleSheet("background-color: rgb(0, 1, 0);\n"
"color: rgb(250, 28, 51);")
        self.ph_disp.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.ph_disp.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ph_disp.setScaledContents(False)
        self.ph_disp.setAlignment(QtCore.Qt.AlignCenter)
        self.ph_disp.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.ph_disp.setObjectName("ph_disp")
        self.gridLayout.addWidget(self.ph_disp, 5, 3, 1, 1)
        self.TC = QtWidgets.QComboBox(Panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TC.sizePolicy().hasHeightForWidth())
        self.TC.setSizePolicy(sizePolicy)
        self.TC.setObjectName("TC")
        self.TC.addItem("")
        self.TC.addItem("")
        self.TC.addItem("")
        self.TC.addItem("")
        self.TC.addItem("")
        self.TC.addItem("")
        self.TC.addItem("")
        self.TC.addItem("")
        self.TC.addItem("")
        self.TC.addItem("")
        self.TC.addItem("")
        self.TC.addItem("")
        self.TC.addItem("")
        self.TC.addItem("")
        self.TC.addItem("")
        self.TC.addItem("")
        self.TC.addItem("")
        self.TC.addItem("")
        self.TC.addItem("")
        self.TC.addItem("")
        self.gridLayout.addWidget(self.TC, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.filter = QtWidgets.QComboBox(Panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filter.sizePolicy().hasHeightForWidth())
        self.filter.setSizePolicy(sizePolicy)
        self.filter.setObjectName("filter")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.gridLayout.addWidget(self.filter, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Panel)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 2, 1, 1)
        self.ref_source = QtWidgets.QComboBox(Panel)
        self.ref_source.setObjectName("ref_source")
        self.ref_source.addItem("")
        self.ref_source.addItem("")
        self.gridLayout.addWidget(self.ref_source, 6, 2, 1, 1)
        self.refresh_rate = QtWidgets.QDoubleSpinBox(Panel)
        self.refresh_rate.setMinimumSize(QtCore.QSize(91, 0))
        self.refresh_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.refresh_rate.setDecimals(1)
        self.refresh_rate.setMaximum(9999999.0)
        self.refresh_rate.setSingleStep(0.5)
        self.refresh_rate.setProperty("value", 2.0)
        self.refresh_rate.setObjectName("refresh_rate")
        self.gridLayout.addWidget(self.refresh_rate, 6, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(Panel)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.gridLayout.addWidget(self.label_47, 5, 1, 1, 1)
        self.monitor = QtWidgets.QCheckBox(Panel)
        self.monitor.setChecked(False)
        self.monitor.setObjectName("monitor")
        self.gridLayout.addWidget(self.monitor, 4, 1, 1, 1)
        self.channel_2 = QtWidgets.QComboBox(Panel)
        self.channel_2.setObjectName("channel_2")
        self.channel_2.addItem("")
        self.channel_2.addItem("")
        self.channel_2.addItem("")
        self.channel_2.addItem("")
        self.channel_2.addItem("")
        self.gridLayout.addWidget(self.channel_2, 1, 2, 1, 1)

        self.retranslateUi(Panel)
        self.monitor.clicked['bool'].connect(Panel.monitor)
        self.doubleSpinBox.valueChanged['double'].connect(Panel.change_f)
        self.doubleSpinBox_2.valueChanged['double'].connect(Panel.change_A)
        self.doubleSpinBox_3.valueChanged['double'].connect(Panel.change_ph)
        self.refresh_rate.valueChanged['double'].connect(Panel.update_timer_timeout)
        self.channel.activated['QString'].connect(Panel.change_x)
        self.sense.activated['int'].connect(Panel.change_s)
        self.TC.activated['int'].connect(Panel.change_TC)
        self.filter.activated['int'].connect(Panel.change_filter)
        self.ref_source.activated['QString'].connect(Panel.change_ref)
        self.channel_2.activated['QString'].connect(Panel.change_y)
        QtCore.QMetaObject.connectSlotsByName(Panel)

    def retranslateUi(self, Panel):
        _translate = QtCore.QCoreApplication.translate
        Panel.setWindowTitle(_translate("Panel", "SRS 830"))
        self.channel.setItemText(0, _translate("Panel", "X"))
        self.channel.setItemText(1, _translate("Panel", "R"))
        self.channel.setItemText(2, _translate("Panel", "X Noise"))
        self.channel.setItemText(3, _translate("Panel", "Aux In 1"))
        self.channel.setItemText(4, _translate("Panel", "Aux In 2"))
        self.doubleSpinBox.setSuffix(_translate("Panel", " Hz"))
        self.label_2.setText(_translate("Panel", "Time constant"))
        self.label.setText(_translate("Panel", "Sensitivity"))
        self.x_disp.setText(_translate("Panel", "--- V"))
        self.y_disp.setText(_translate("Panel", "--- V"))
        self.f_disp.setText(_translate("Panel", "--- Hz"))
        self.sense.setItemText(0, _translate("Panel", "2 nV/fA"))
        self.sense.setItemText(1, _translate("Panel", "5 nV/fA"))
        self.sense.setItemText(2, _translate("Panel", "10 nV/fA"))
        self.sense.setItemText(3, _translate("Panel", "20 nV/fA"))
        self.sense.setItemText(4, _translate("Panel", "50 nV/fA"))
        self.sense.setItemText(5, _translate("Panel", "100 nV/fA"))
        self.sense.setItemText(6, _translate("Panel", "200 nV/fA"))
        self.sense.setItemText(7, _translate("Panel", "500 nV/fA"))
        self.sense.setItemText(8, _translate("Panel", "1 μV/pA"))
        self.sense.setItemText(9, _translate("Panel", "2 μV/pA"))
        self.sense.setItemText(10, _translate("Panel", "5 μV/pA"))
        self.sense.setItemText(11, _translate("Panel", "10 μV/pA"))
        self.sense.setItemText(12, _translate("Panel", "20 μV/pA"))
        self.sense.setItemText(13, _translate("Panel", "50 μV/pA"))
        self.sense.setItemText(14, _translate("Panel", "100 μV/pA"))
        self.sense.setItemText(15, _translate("Panel", "200 μV/pA"))
        self.sense.setItemText(16, _translate("Panel", "500 μV/pA"))
        self.sense.setItemText(17, _translate("Panel", "1 mV/nA"))
        self.sense.setItemText(18, _translate("Panel", "2 mV/nA"))
        self.sense.setItemText(19, _translate("Panel", "5 mV/nA"))
        self.sense.setItemText(20, _translate("Panel", "10 mV/nA"))
        self.sense.setItemText(21, _translate("Panel", "20 mV/nA"))
        self.sense.setItemText(22, _translate("Panel", "50 mV/nA"))
        self.sense.setItemText(23, _translate("Panel", "100 mV/nA"))
        self.sense.setItemText(24, _translate("Panel", "200 mV/nA"))
        self.sense.setItemText(25, _translate("Panel", "500 mV/nA"))
        self.sense.setItemText(26, _translate("Panel", "1 V/μA"))
        self.a_disp.setText(_translate("Panel", "--- V"))
        self.doubleSpinBox_3.setSuffix(_translate("Panel", " deg"))
        self.doubleSpinBox_2.setSuffix(_translate("Panel", " V"))
        self.ph_disp.setText(_translate("Panel", "--- deg"))
        self.TC.setItemText(0, _translate("Panel", "10 μs"))
        self.TC.setItemText(1, _translate("Panel", "30 μs"))
        self.TC.setItemText(2, _translate("Panel", "100 μs"))
        self.TC.setItemText(3, _translate("Panel", "300 μs"))
        self.TC.setItemText(4, _translate("Panel", "1 ms"))
        self.TC.setItemText(5, _translate("Panel", "3 ms"))
        self.TC.setItemText(6, _translate("Panel", "10 ms"))
        self.TC.setItemText(7, _translate("Panel", "30 ms"))
        self.TC.setItemText(8, _translate("Panel", "100 ms"))
        self.TC.setItemText(9, _translate("Panel", "300 ms"))
        self.TC.setItemText(10, _translate("Panel", "1 s"))
        self.TC.setItemText(11, _translate("Panel", "3 s"))
        self.TC.setItemText(12, _translate("Panel", "10 s"))
        self.TC.setItemText(13, _translate("Panel", "30 s"))
        self.TC.setItemText(14, _translate("Panel", "100 s"))
        self.TC.setItemText(15, _translate("Panel", "300 s"))
        self.TC.setItemText(16, _translate("Panel", "1 ks"))
        self.TC.setItemText(17, _translate("Panel", "3 ks"))
        self.TC.setItemText(18, _translate("Panel", "10 ks"))
        self.TC.setItemText(19, _translate("Panel", "30 ks"))
        self.label_3.setText(_translate("Panel", "Filter"))
        self.filter.setItemText(0, _translate("Panel", "6 dB/oct"))
        self.filter.setItemText(1, _translate("Panel", "12 dB/oct"))
        self.filter.setItemText(2, _translate("Panel", "18 dB/oct"))
        self.filter.setItemText(3, _translate("Panel", "24 dB/oct"))
        self.label_4.setText(_translate("Panel", "Reference Source"))
        self.ref_source.setItemText(0, _translate("Panel", "External"))
        self.ref_source.setItemText(1, _translate("Panel", "Internal"))
        self.refresh_rate.setSuffix(_translate("Panel", " secs"))
        self.label_47.setText(_translate("Panel", "Refresh rate"))
        self.monitor.setText(_translate("Panel", "Monitor"))
        self.channel_2.setItemText(0, _translate("Panel", "Y"))
        self.channel_2.setItemText(1, _translate("Panel", "theta"))
        self.channel_2.setItemText(2, _translate("Panel", "Y Noise"))
        self.channel_2.setItemText(3, _translate("Panel", "Aux In 3"))
        self.channel_2.setItemText(4, _translate("Panel", "Aux In 4"))

