# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyGMI_files\Instruments_panels\SR830.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Panel(object):
    def setupUi(self, Panel):
        Panel.setObjectName(_fromUtf8("Panel"))
        Panel.resize(486, 162)
        self.gridLayout = QtGui.QGridLayout(Panel)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.channel = QtGui.QComboBox(Panel)
        self.channel.setObjectName(_fromUtf8("channel"))
        self.channel.addItem(_fromUtf8(""))
        self.channel.addItem(_fromUtf8(""))
        self.channel.addItem(_fromUtf8(""))
        self.channel.addItem(_fromUtf8(""))
        self.channel.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.channel, 1, 1, 1, 1)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(Panel)
        self.doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox.setDecimals(4)
        self.doubleSpinBox.setMaximum(200000.0)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.gridLayout.addWidget(self.doubleSpinBox, 1, 3, 1, 1)
        self.label_2 = QtGui.QLabel(Panel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label = QtGui.QLabel(Panel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.x_disp = QtGui.QLabel(Panel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_disp.sizePolicy().hasHeightForWidth())
        self.x_disp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.x_disp.setFont(font)
        self.x_disp.setAutoFillBackground(False)
        self.x_disp.setStyleSheet(_fromUtf8("background-color: rgb(0, 1, 0);\n"
"color: rgb(250, 28, 51);"))
        self.x_disp.setFrameShape(QtGui.QFrame.WinPanel)
        self.x_disp.setFrameShadow(QtGui.QFrame.Sunken)
        self.x_disp.setScaledContents(False)
        self.x_disp.setAlignment(QtCore.Qt.AlignCenter)
        self.x_disp.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.x_disp.setObjectName(_fromUtf8("x_disp"))
        self.gridLayout.addWidget(self.x_disp, 0, 1, 1, 1)
        self.y_disp = QtGui.QLabel(Panel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_disp.sizePolicy().hasHeightForWidth())
        self.y_disp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.y_disp.setFont(font)
        self.y_disp.setAutoFillBackground(False)
        self.y_disp.setStyleSheet(_fromUtf8("background-color: rgb(0, 1, 0);\n"
"color: rgb(250, 28, 51);"))
        self.y_disp.setFrameShape(QtGui.QFrame.WinPanel)
        self.y_disp.setFrameShadow(QtGui.QFrame.Sunken)
        self.y_disp.setScaledContents(False)
        self.y_disp.setAlignment(QtCore.Qt.AlignCenter)
        self.y_disp.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.y_disp.setObjectName(_fromUtf8("y_disp"))
        self.gridLayout.addWidget(self.y_disp, 0, 2, 1, 1)
        self.f_disp = QtGui.QLabel(Panel)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.f_disp.setFont(font)
        self.f_disp.setAutoFillBackground(False)
        self.f_disp.setStyleSheet(_fromUtf8("background-color: rgb(0, 1, 0);\n"
"color: rgb(250, 28, 51);"))
        self.f_disp.setFrameShape(QtGui.QFrame.WinPanel)
        self.f_disp.setFrameShadow(QtGui.QFrame.Sunken)
        self.f_disp.setScaledContents(False)
        self.f_disp.setAlignment(QtCore.Qt.AlignCenter)
        self.f_disp.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.f_disp.setObjectName(_fromUtf8("f_disp"))
        self.gridLayout.addWidget(self.f_disp, 0, 3, 1, 1)
        self.sense = QtGui.QComboBox(Panel)
        self.sense.setObjectName(_fromUtf8("sense"))
        self.sense.addItem(_fromUtf8(""))
        self.sense.addItem(_fromUtf8(""))
        self.sense.addItem(_fromUtf8(""))
        self.sense.addItem(_fromUtf8(""))
        self.sense.addItem(_fromUtf8(""))
        self.sense.addItem(_fromUtf8(""))
        self.sense.addItem(_fromUtf8(""))
        self.sense.addItem(_fromUtf8(""))
        self.sense.addItem(_fromUtf8(""))
        self.sense.addItem(_fromUtf8(""))
        self.sense.addItem(_fromUtf8(""))
        self.sense.addItem(_fromUtf8(""))
        self.sense.addItem(_fromUtf8(""))
        self.sense.addItem(_fromUtf8(""))
        self.sense.addItem(_fromUtf8(""))
        self.sense.addItem(_fromUtf8(""))
        self.sense.addItem(_fromUtf8(""))
        self.sense.addItem(_fromUtf8(""))
        self.sense.addItem(_fromUtf8(""))
        self.sense.addItem(_fromUtf8(""))
        self.sense.addItem(_fromUtf8(""))
        self.sense.addItem(_fromUtf8(""))
        self.sense.addItem(_fromUtf8(""))
        self.sense.addItem(_fromUtf8(""))
        self.sense.addItem(_fromUtf8(""))
        self.sense.addItem(_fromUtf8(""))
        self.sense.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.sense, 1, 0, 1, 1)
        self.a_disp = QtGui.QLabel(Panel)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.a_disp.setFont(font)
        self.a_disp.setAutoFillBackground(False)
        self.a_disp.setStyleSheet(_fromUtf8("background-color: rgb(0, 1, 0);\n"
"color: rgb(250, 28, 51);"))
        self.a_disp.setFrameShape(QtGui.QFrame.WinPanel)
        self.a_disp.setFrameShadow(QtGui.QFrame.Sunken)
        self.a_disp.setScaledContents(False)
        self.a_disp.setAlignment(QtCore.Qt.AlignCenter)
        self.a_disp.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.a_disp.setObjectName(_fromUtf8("a_disp"))
        self.gridLayout.addWidget(self.a_disp, 3, 3, 1, 1)
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(Panel)
        self.doubleSpinBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_3.setDecimals(3)
        self.doubleSpinBox_3.setMinimum(-20000.0)
        self.doubleSpinBox_3.setMaximum(20000.0)
        self.doubleSpinBox_3.setSingleStep(0.01)
        self.doubleSpinBox_3.setProperty("value", 0.0)
        self.doubleSpinBox_3.setObjectName(_fromUtf8("doubleSpinBox_3"))
        self.gridLayout.addWidget(self.doubleSpinBox_3, 6, 3, 1, 1)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(Panel)
        self.doubleSpinBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_2.setDecimals(3)
        self.doubleSpinBox_2.setMinimum(0.0)
        self.doubleSpinBox_2.setMaximum(200000.0)
        self.doubleSpinBox_2.setSingleStep(0.01)
        self.doubleSpinBox_2.setProperty("value", 0.0)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.gridLayout.addWidget(self.doubleSpinBox_2, 4, 3, 1, 1)
        self.ph_disp = QtGui.QLabel(Panel)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.ph_disp.setFont(font)
        self.ph_disp.setAutoFillBackground(False)
        self.ph_disp.setStyleSheet(_fromUtf8("background-color: rgb(0, 1, 0);\n"
"color: rgb(250, 28, 51);"))
        self.ph_disp.setFrameShape(QtGui.QFrame.WinPanel)
        self.ph_disp.setFrameShadow(QtGui.QFrame.Sunken)
        self.ph_disp.setScaledContents(False)
        self.ph_disp.setAlignment(QtCore.Qt.AlignCenter)
        self.ph_disp.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.ph_disp.setObjectName(_fromUtf8("ph_disp"))
        self.gridLayout.addWidget(self.ph_disp, 5, 3, 1, 1)
        self.TC = QtGui.QComboBox(Panel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TC.sizePolicy().hasHeightForWidth())
        self.TC.setSizePolicy(sizePolicy)
        self.TC.setObjectName(_fromUtf8("TC"))
        self.TC.addItem(_fromUtf8(""))
        self.TC.addItem(_fromUtf8(""))
        self.TC.addItem(_fromUtf8(""))
        self.TC.addItem(_fromUtf8(""))
        self.TC.addItem(_fromUtf8(""))
        self.TC.addItem(_fromUtf8(""))
        self.TC.addItem(_fromUtf8(""))
        self.TC.addItem(_fromUtf8(""))
        self.TC.addItem(_fromUtf8(""))
        self.TC.addItem(_fromUtf8(""))
        self.TC.addItem(_fromUtf8(""))
        self.TC.addItem(_fromUtf8(""))
        self.TC.addItem(_fromUtf8(""))
        self.TC.addItem(_fromUtf8(""))
        self.TC.addItem(_fromUtf8(""))
        self.TC.addItem(_fromUtf8(""))
        self.TC.addItem(_fromUtf8(""))
        self.TC.addItem(_fromUtf8(""))
        self.TC.addItem(_fromUtf8(""))
        self.TC.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.TC, 4, 0, 1, 1)
        self.label_3 = QtGui.QLabel(Panel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.filter = QtGui.QComboBox(Panel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filter.sizePolicy().hasHeightForWidth())
        self.filter.setSizePolicy(sizePolicy)
        self.filter.setObjectName(_fromUtf8("filter"))
        self.filter.addItem(_fromUtf8(""))
        self.filter.addItem(_fromUtf8(""))
        self.filter.addItem(_fromUtf8(""))
        self.filter.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.filter, 6, 0, 1, 1)
        self.label_4 = QtGui.QLabel(Panel)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 5, 2, 1, 1)
        self.ref_source = QtGui.QComboBox(Panel)
        self.ref_source.setObjectName(_fromUtf8("ref_source"))
        self.ref_source.addItem(_fromUtf8(""))
        self.ref_source.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.ref_source, 6, 2, 1, 1)
        self.refresh_rate = QtGui.QDoubleSpinBox(Panel)
        self.refresh_rate.setMinimumSize(QtCore.QSize(91, 0))
        self.refresh_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.refresh_rate.setDecimals(1)
        self.refresh_rate.setMaximum(9999999.0)
        self.refresh_rate.setSingleStep(0.5)
        self.refresh_rate.setProperty("value", 2.0)
        self.refresh_rate.setObjectName(_fromUtf8("refresh_rate"))
        self.gridLayout.addWidget(self.refresh_rate, 6, 1, 1, 1)
        self.label_47 = QtGui.QLabel(Panel)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout.addWidget(self.label_47, 5, 1, 1, 1)
        self.monitor = QtGui.QCheckBox(Panel)
        self.monitor.setChecked(False)
        self.monitor.setObjectName(_fromUtf8("monitor"))
        self.gridLayout.addWidget(self.monitor, 4, 1, 1, 1)
        self.channel_2 = QtGui.QComboBox(Panel)
        self.channel_2.setObjectName(_fromUtf8("channel_2"))
        self.channel_2.addItem(_fromUtf8(""))
        self.channel_2.addItem(_fromUtf8(""))
        self.channel_2.addItem(_fromUtf8(""))
        self.channel_2.addItem(_fromUtf8(""))
        self.channel_2.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.channel_2, 1, 2, 1, 1)

        self.retranslateUi(Panel)
        QtCore.QObject.connect(self.monitor, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), Panel.monitor)
        QtCore.QObject.connect(self.doubleSpinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), Panel.change_f)
        QtCore.QObject.connect(self.doubleSpinBox_2, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), Panel.change_A)
        QtCore.QObject.connect(self.doubleSpinBox_3, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), Panel.change_ph)
        QtCore.QObject.connect(self.refresh_rate, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), Panel.update_timer_timeout)
        QtCore.QObject.connect(self.channel, QtCore.SIGNAL(_fromUtf8("activated(QString)")), Panel.change_x)
        QtCore.QObject.connect(self.sense, QtCore.SIGNAL(_fromUtf8("activated(int)")), Panel.change_s)
        QtCore.QObject.connect(self.TC, QtCore.SIGNAL(_fromUtf8("activated(int)")), Panel.change_TC)
        QtCore.QObject.connect(self.filter, QtCore.SIGNAL(_fromUtf8("activated(int)")), Panel.change_filter)
        QtCore.QObject.connect(self.ref_source, QtCore.SIGNAL(_fromUtf8("activated(QString)")), Panel.change_ref)
        QtCore.QObject.connect(self.channel_2, QtCore.SIGNAL(_fromUtf8("activated(QString)")), Panel.change_y)
        QtCore.QMetaObject.connectSlotsByName(Panel)

    def retranslateUi(self, Panel):
        Panel.setWindowTitle(_translate("Panel", "SRS 830", None))
        self.channel.setItemText(0, _translate("Panel", "X", None))
        self.channel.setItemText(1, _translate("Panel", "R", None))
        self.channel.setItemText(2, _translate("Panel", "X Noise", None))
        self.channel.setItemText(3, _translate("Panel", "Aux In 1", None))
        self.channel.setItemText(4, _translate("Panel", "Aux In 2", None))
        self.doubleSpinBox.setSuffix(_translate("Panel", " Hz", None))
        self.label_2.setText(_translate("Panel", "Time constant", None))
        self.label.setText(_translate("Panel", "Sensitivity", None))
        self.x_disp.setText(_translate("Panel", "--- V", None))
        self.y_disp.setText(_translate("Panel", "--- V", None))
        self.f_disp.setText(_translate("Panel", "--- Hz", None))
        self.sense.setItemText(0, _translate("Panel", "2 nV/fA", None))
        self.sense.setItemText(1, _translate("Panel", "5 nV/fA", None))
        self.sense.setItemText(2, _translate("Panel", "10 nV/fA", None))
        self.sense.setItemText(3, _translate("Panel", "20 nV/fA", None))
        self.sense.setItemText(4, _translate("Panel", "50 nV/fA", None))
        self.sense.setItemText(5, _translate("Panel", "100 nV/fA", None))
        self.sense.setItemText(6, _translate("Panel", "200 nV/fA", None))
        self.sense.setItemText(7, _translate("Panel", "500 nV/fA", None))
        self.sense.setItemText(8, _translate("Panel", "1 μV/pA", None))
        self.sense.setItemText(9, _translate("Panel", "2 μV/pA", None))
        self.sense.setItemText(10, _translate("Panel", "5 μV/pA", None))
        self.sense.setItemText(11, _translate("Panel", "10 μV/pA", None))
        self.sense.setItemText(12, _translate("Panel", "20 μV/pA", None))
        self.sense.setItemText(13, _translate("Panel", "50 μV/pA", None))
        self.sense.setItemText(14, _translate("Panel", "100 μV/pA", None))
        self.sense.setItemText(15, _translate("Panel", "200 μV/pA", None))
        self.sense.setItemText(16, _translate("Panel", "500 μV/pA", None))
        self.sense.setItemText(17, _translate("Panel", "1 mV/nA", None))
        self.sense.setItemText(18, _translate("Panel", "2 mV/nA", None))
        self.sense.setItemText(19, _translate("Panel", "5 mV/nA", None))
        self.sense.setItemText(20, _translate("Panel", "10 mV/nA", None))
        self.sense.setItemText(21, _translate("Panel", "20 mV/nA", None))
        self.sense.setItemText(22, _translate("Panel", "50 mV/nA", None))
        self.sense.setItemText(23, _translate("Panel", "100 mV/nA", None))
        self.sense.setItemText(24, _translate("Panel", "200 mV/nA", None))
        self.sense.setItemText(25, _translate("Panel", "500 mV/nA", None))
        self.sense.setItemText(26, _translate("Panel", "1 V/μA", None))
        self.a_disp.setText(_translate("Panel", "--- V", None))
        self.doubleSpinBox_3.setSuffix(_translate("Panel", " deg", None))
        self.doubleSpinBox_2.setSuffix(_translate("Panel", " V", None))
        self.ph_disp.setText(_translate("Panel", "--- deg", None))
        self.TC.setItemText(0, _translate("Panel", "10 μs", None))
        self.TC.setItemText(1, _translate("Panel", "30 μs", None))
        self.TC.setItemText(2, _translate("Panel", "100 μs", None))
        self.TC.setItemText(3, _translate("Panel", "300 μs", None))
        self.TC.setItemText(4, _translate("Panel", "1 ms", None))
        self.TC.setItemText(5, _translate("Panel", "3 ms", None))
        self.TC.setItemText(6, _translate("Panel", "10 ms", None))
        self.TC.setItemText(7, _translate("Panel", "30 ms", None))
        self.TC.setItemText(8, _translate("Panel", "100 ms", None))
        self.TC.setItemText(9, _translate("Panel", "300 ms", None))
        self.TC.setItemText(10, _translate("Panel", "1 s", None))
        self.TC.setItemText(11, _translate("Panel", "3 s", None))
        self.TC.setItemText(12, _translate("Panel", "10 s", None))
        self.TC.setItemText(13, _translate("Panel", "30 s", None))
        self.TC.setItemText(14, _translate("Panel", "100 s", None))
        self.TC.setItemText(15, _translate("Panel", "300 s", None))
        self.TC.setItemText(16, _translate("Panel", "1 ks", None))
        self.TC.setItemText(17, _translate("Panel", "3 ks", None))
        self.TC.setItemText(18, _translate("Panel", "10 ks", None))
        self.TC.setItemText(19, _translate("Panel", "30 ks", None))
        self.label_3.setText(_translate("Panel", "Filter", None))
        self.filter.setItemText(0, _translate("Panel", "6 dB/oct", None))
        self.filter.setItemText(1, _translate("Panel", "12 dB/oct", None))
        self.filter.setItemText(2, _translate("Panel", "18 dB/oct", None))
        self.filter.setItemText(3, _translate("Panel", "24 dB/oct", None))
        self.label_4.setText(_translate("Panel", "Reference Source", None))
        self.ref_source.setItemText(0, _translate("Panel", "External", None))
        self.ref_source.setItemText(1, _translate("Panel", "Internal", None))
        self.refresh_rate.setSuffix(_translate("Panel", " secs", None))
        self.label_47.setText(_translate("Panel", "Refresh rate", None))
        self.monitor.setText(_translate("Panel", "Monitor", None))
        self.channel_2.setItemText(0, _translate("Panel", "Y", None))
        self.channel_2.setItemText(1, _translate("Panel", "theta", None))
        self.channel_2.setItemText(2, _translate("Panel", "Y Noise", None))
        self.channel_2.setItemText(3, _translate("Panel", "Aux In 3", None))
        self.channel_2.setItemText(4, _translate("Panel", "Aux In 4", None))

